import type { FormField } from '@/shared/components/form';

/**
 * Vehicle and vessel have no field config on the appraisal side at all — the only ones in
 * the codebase are the request module's intake shapes, which are four fields with different
 * names. These are authored from the C# detail VOs: type follows the property type, and
 * anything that should really be a dropdown (energy use, condition, vessel type…) is a plain
 * input until someone supplies the parameter group.
 */
export const vehicleCorrectionFields: FormField[] = [
  {
    type: 'text-input',
    label: 'Property Name',
    name: 'propertyName',
    wrapperClassName: 'col-span-3',
  },
  {
    type: 'text-input',
    label: 'Vehicle Name',
    name: 'vehicleName',
    wrapperClassName: 'col-span-3',
  },
  { type: 'text-input', label: 'Engine No', name: 'engineNo', wrapperClassName: 'col-span-3' },
  { type: 'text-input', label: 'Chassis No', name: 'chassisNo', wrapperClassName: 'col-span-3' },
  {
    type: 'text-input',
    label: 'Registration Number',
    name: 'registrationNumber',
    wrapperClassName: 'col-span-3',
  },
  { type: 'text-input', label: 'Brand', name: 'brand', wrapperClassName: 'col-span-3' },
  { type: 'text-input', label: 'Model', name: 'model', wrapperClassName: 'col-span-3' },
  {
    type: 'number-input',
    label: 'Year Of Manufacture',
    name: 'yearOfManufacture',
    wrapperClassName: 'col-span-3',
  },
  {
    type: 'text-input',
    label: 'Country Of Manufacture',
    name: 'countryOfManufacture',
    wrapperClassName: 'col-span-3',
  },
  {
    type: 'date-input',
    label: 'Purchase Date',
    name: 'purchaseDate',
    wrapperClassName: 'col-span-3',
  },
  {
    type: 'number-input',
    label: 'Purchase Price',
    name: 'purchasePrice',
    wrapperClassName: 'col-span-3',
  },
  { type: 'text-input', label: 'Capacity', name: 'capacity', wrapperClassName: 'col-span-3' },
  { type: 'number-input', label: 'Width', name: 'width', wrapperClassName: 'col-span-3' },
  { type: 'number-input', label: 'Length', name: 'length', wrapperClassName: 'col-span-3' },
  { type: 'number-input', label: 'Height', name: 'height', wrapperClassName: 'col-span-3' },
  { type: 'text-input', label: 'Energy Use', name: 'energyUse', wrapperClassName: 'col-span-3' },
  {
    type: 'text-input',
    label: 'Energy Use Remark',
    name: 'energyUseRemark',
    wrapperClassName: 'col-span-3',
  },
  { type: 'text-input', label: 'Owner Name', name: 'ownerName', wrapperClassName: 'col-span-3' },
  {
    type: 'checkbox',
    label: 'Is Owner Verified',
    name: 'isOwnerVerified',
    wrapperClassName: 'col-span-3',
  },
  { type: 'checkbox', label: 'Can Use', name: 'canUse', wrapperClassName: 'col-span-3' },
  { type: 'text-input', label: 'Location', name: 'location', wrapperClassName: 'col-span-3' },
  {
    type: 'text-input',
    label: 'Condition Use',
    name: 'conditionUse',
    wrapperClassName: 'col-span-3',
  },
  {
    type: 'text-input',
    label: 'Vehicle Condition',
    name: 'vehicleCondition',
    wrapperClassName: 'col-span-3',
  },
  {
    type: 'number-input',
    label: 'Vehicle Age',
    name: 'vehicleAge',
    wrapperClassName: 'col-span-3',
  },
  {
    type: 'text-input',
    label: 'Vehicle Efficiency',
    name: 'vehicleEfficiency',
    wrapperClassName: 'col-span-3',
  },
  {
    type: 'text-input',
    label: 'Vehicle Technology',
    name: 'vehicleTechnology',
    wrapperClassName: 'col-span-3',
  },
  { type: 'text-input', label: 'Use Purpose', name: 'usePurpose', wrapperClassName: 'col-span-3' },
  {
    type: 'text-input',
    label: 'Vehicle Part',
    name: 'vehiclePart',
    wrapperClassName: 'col-span-3',
  },
  { type: 'text-input', label: 'Remark', name: 'remark', wrapperClassName: 'col-span-3' },
  { type: 'text-input', label: 'Other', name: 'other', wrapperClassName: 'col-span-3' },
  {
    type: 'text-input',
    label: 'Appraiser Opinion',
    name: 'appraiserOpinion',
    wrapperClassName: 'col-span-3',
  },
];

export const vesselCorrectionFields: FormField[] = [
  {
    type: 'text-input',
    label: 'Property Name',
    name: 'propertyName',
    wrapperClassName: 'col-span-3',
  },
  { type: 'text-input', label: 'Vessel Name', name: 'vesselName', wrapperClassName: 'col-span-3' },
  { type: 'text-input', label: 'Engine No', name: 'engineNo', wrapperClassName: 'col-span-3' },
  {
    type: 'text-input',
    label: 'Registration Number',
    name: 'registrationNumber',
    wrapperClassName: 'col-span-3',
  },
  {
    type: 'date-input',
    label: 'Registration Date',
    name: 'registrationDate',
    wrapperClassName: 'col-span-3',
  },
  { type: 'text-input', label: 'Brand', name: 'brand', wrapperClassName: 'col-span-3' },
  { type: 'text-input', label: 'Model', name: 'model', wrapperClassName: 'col-span-3' },
  {
    type: 'number-input',
    label: 'Year Of Manufacture',
    name: 'yearOfManufacture',
    wrapperClassName: 'col-span-3',
  },
  {
    type: 'text-input',
    label: 'Place Of Manufacture',
    name: 'placeOfManufacture',
    wrapperClassName: 'col-span-3',
  },
  { type: 'text-input', label: 'Vessel Type', name: 'vesselType', wrapperClassName: 'col-span-3' },
  {
    type: 'text-input',
    label: 'Class Of Vessel',
    name: 'classOfVessel',
    wrapperClassName: 'col-span-3',
  },
  {
    type: 'date-input',
    label: 'Purchase Date',
    name: 'purchaseDate',
    wrapperClassName: 'col-span-3',
  },
  {
    type: 'number-input',
    label: 'Purchase Price',
    name: 'purchasePrice',
    wrapperClassName: 'col-span-3',
  },
  {
    type: 'text-input',
    label: 'Engine Capacity',
    name: 'engineCapacity',
    wrapperClassName: 'col-span-3',
  },
  { type: 'number-input', label: 'Width', name: 'width', wrapperClassName: 'col-span-3' },
  { type: 'number-input', label: 'Length', name: 'length', wrapperClassName: 'col-span-3' },
  { type: 'number-input', label: 'Height', name: 'height', wrapperClassName: 'col-span-3' },
  {
    type: 'number-input',
    label: 'Gross Tonnage',
    name: 'grossTonnage',
    wrapperClassName: 'col-span-3',
  },
  {
    type: 'number-input',
    label: 'Net Tonnage',
    name: 'netTonnage',
    wrapperClassName: 'col-span-3',
  },
  { type: 'text-input', label: 'Energy Use', name: 'energyUse', wrapperClassName: 'col-span-3' },
  {
    type: 'text-input',
    label: 'Energy Use Remark',
    name: 'energyUseRemark',
    wrapperClassName: 'col-span-3',
  },
  { type: 'text-input', label: 'Owner Name', name: 'ownerName', wrapperClassName: 'col-span-3' },
  {
    type: 'checkbox',
    label: 'Is Owner Verified',
    name: 'isOwnerVerified',
    wrapperClassName: 'col-span-3',
  },
  { type: 'checkbox', label: 'Can Use', name: 'canUse', wrapperClassName: 'col-span-3' },
  { type: 'text-input', label: 'Former Name', name: 'formerName', wrapperClassName: 'col-span-3' },
  {
    type: 'text-input',
    label: 'Vessel Current Name',
    name: 'vesselCurrentName',
    wrapperClassName: 'col-span-3',
  },
  { type: 'text-input', label: 'Location', name: 'location', wrapperClassName: 'col-span-3' },
  {
    type: 'text-input',
    label: 'Condition Use',
    name: 'conditionUse',
    wrapperClassName: 'col-span-3',
  },
  {
    type: 'text-input',
    label: 'Vessel Condition',
    name: 'vesselCondition',
    wrapperClassName: 'col-span-3',
  },
  { type: 'number-input', label: 'Vessel Age', name: 'vesselAge', wrapperClassName: 'col-span-3' },
  {
    type: 'text-input',
    label: 'Vessel Efficiency',
    name: 'vesselEfficiency',
    wrapperClassName: 'col-span-3',
  },
  {
    type: 'text-input',
    label: 'Vessel Technology',
    name: 'vesselTechnology',
    wrapperClassName: 'col-span-3',
  },
  { type: 'text-input', label: 'Use Purpose', name: 'usePurpose', wrapperClassName: 'col-span-3' },
  { type: 'text-input', label: 'Vessel Part', name: 'vesselPart', wrapperClassName: 'col-span-3' },
  { type: 'text-input', label: 'Remark', name: 'remark', wrapperClassName: 'col-span-3' },
  { type: 'text-input', label: 'Other', name: 'other', wrapperClassName: 'col-span-3' },
  {
    type: 'text-input',
    label: 'Appraiser Opinion',
    name: 'appraiserOpinion',
    wrapperClassName: 'col-span-3',
  },
];
