import type { GetSupportingDataByIdType } from '../schemas/form';

export const supportingDataDetailPreviewList = [
  {
    id: '01',
    propertyName: 'Lumphini Tower',
    collateralType: '02', // Land with buildings
    latitude: 13.7286,
    longitude: 100.5419,
    houseNo: '1168/21',
    subDistrictName: 'Lumphini',
    districtName: 'Pathum Wan',
    provinceName: 'Bangkok',
  },
  {
    id: '02',
    propertyName: 'Silom Complex',
    collateralType: '05', // Buildings
    latitude: 13.7286,
    longitude: 100.534,
    houseNo: '191',
    subDistrictName: 'Silom',
    districtName: 'Bang Rak',
    provinceName: 'Bangkok',
  },
  {
    id: '03',
    propertyName: 'Sukhumvit Garden Residence',
    collateralType: '08', // Apartment
    latitude: 13.7308,
    longitude: 100.5697,
    houseNo: '22/15',
    subDistrictName: 'Khlong Tan Nuea',
    districtName: 'Watthana',
    provinceName: 'Bangkok',
  },
  {
    id: '04',
    propertyName: 'Asoke Land Plot',
    collateralType: '01', // Land
    latitude: 13.7376,
    longitude: 100.5602,
    houseNo: '88',
    subDistrictName: 'Khlong Toei Nuea',
    districtName: 'Watthana',
    provinceName: 'Bangkok',
  },
  {
    id: '05',
    propertyName: 'Sathorn Office Building',
    collateralType: '05', // Buildings
    latitude: 13.7234,
    longitude: 100.5292,
    houseNo: '175/3',
    subDistrictName: 'Suriyawong',
    districtName: 'Bang Rak',
    provinceName: 'Bangkok',
  },
  {
    id: '06',
    propertyName: 'Riverside Condominium',
    collateralType: '33', // Condominium (BlockCondo)
    latitude: 13.7268,
    longitude: 100.5101,
    houseNo: '257/45',
    subDistrictName: 'Khlong San',
    districtName: 'Khlong San',
    provinceName: 'Bangkok',
  },
  {
    id: '07',
    propertyName: 'Ratchada Land Allocation',
    collateralType: '04', // Land allocation (whole project)
    latitude: 13.7649,
    longitude: 100.5697,
    houseNo: '120',
    subDistrictName: 'Huai Khwang',
    districtName: 'Huai Khwang',
    provinceName: 'Bangkok',
  },
  {
    id: '08',
    propertyName: 'Pak Kret Townhouse',
    collateralType: '02', // Land with buildings
    latitude: 13.9125,
    longitude: 100.4982,
    houseNo: '99/12',
    subDistrictName: 'Pak Kret',
    districtName: 'Pak Kret',
    provinceName: 'Nonthaburi',
  },
  {
    id: '09',
    propertyName: 'Bang Phut Riverside Land',
    collateralType: '01', // Land
    latitude: 13.9075,
    longitude: 100.4944,
    houseNo: '45/8',
    subDistrictName: 'Bang Phut',
    districtName: 'Pak Kret',
    provinceName: 'Nonthaburi',
  },
  {
    id: '10',
    propertyName: 'Samut Prakan Warehouse',
    collateralType: '05', // Buildings
    latitude: 13.6464,
    longitude: 100.5564,
    houseNo: '333/7',
    subDistrictName: 'Bang Krachao',
    districtName: 'Phra Pradaeng',
    provinceName: 'Samut Prakan',
  },
  {
    id: '11',
    propertyName: 'Pattaya Beach Villa',
    collateralType: '02', // Land with buildings
    latitude: 12.9276,
    longitude: 100.877,
    houseNo: '78/2',
    subDistrictName: 'Nong Prue',
    districtName: 'Bang Lamung',
    provinceName: 'Chonburi',
  },
  {
    id: '12',
    propertyName: 'Na Kluea Seaview Condo',
    collateralType: '33', // Condominium (BlockCondo)
    latitude: 12.9522,
    longitude: 100.8911,
    houseNo: '212/108',
    subDistrictName: 'Na Kluea',
    districtName: 'Bang Lamung',
    provinceName: 'Chonburi',
  },
  {
    id: '13',
    propertyName: 'Chiang Mai Old City House',
    collateralType: '02', // Land with buildings
    latitude: 18.7889,
    longitude: 98.9844,
    houseNo: '14/3',
    subDistrictName: 'Si Phum',
    districtName: 'Mueang Chiang Mai',
    provinceName: 'Chiang Mai',
  },
  {
    id: '14',
    propertyName: 'Suthep Mountain Plot',
    collateralType: '01', // Land
    latitude: 18.7969,
    longitude: 98.9489,
    houseNo: '56',
    subDistrictName: 'Suthep',
    districtName: 'Mueang Chiang Mai',
    provinceName: 'Chiang Mai',
  },
  {
    id: '15',
    propertyName: 'Patong Beach Hotel',
    collateralType: '07', // Building (whole project)
    latitude: 7.8961,
    longitude: 98.2966,
    houseNo: '88/99',
    subDistrictName: 'Pa Tong',
    districtName: 'Kathu',
    provinceName: 'Phuket',
  },
  {
    id: '16',
    propertyName: 'Karon Resort Land',
    collateralType: '01', // Land
    latitude: 7.8458,
    longitude: 98.2942,
    houseNo: '101/5',
    subDistrictName: 'Karon',
    districtName: 'Mueang Phuket',
    provinceName: 'Phuket',
  },
  {
    id: '17',
    propertyName: 'Rawai Leasehold Estate',
    collateralType: '25', // Leasehold rights (land with buildings)
    latitude: 7.7758,
    longitude: 98.3275,
    houseNo: '67/12',
    subDistrictName: 'Rawai',
    districtName: 'Mueang Phuket',
    provinceName: 'Phuket',
  },
  {
    id: '18',
    propertyName: 'Bangkok Logistics Truck Fleet',
    collateralType: '10', // Car
    latitude: 13.6904,
    longitude: 100.7501,
    houseNo: '999/1',
    subDistrictName: 'Khlong Sam Prawet',
    districtName: 'Lat Krabang',
    provinceName: 'Bangkok',
  },
  {
    id: '19',
    propertyName: 'Industrial CNC Machinery',
    collateralType: '11', // Machinery
    latitude: 13.6464,
    longitude: 100.7032,
    houseNo: '444/22',
    subDistrictName: 'Bang Pu Mai',
    districtName: 'Mueang Samut Prakan',
    provinceName: 'Samut Prakan',
  },
  {
    id: '20',
    propertyName: 'Chao Phraya Cargo Vessel',
    collateralType: '12', // Ship
    latitude: 13.599,
    longitude: 100.5436,
    houseNo: '5',
    subDistrictName: 'Tha Chin',
    districtName: 'Mueang Samut Sakhon',
    provinceName: 'Samut Sakhon',
  },
];

export const supportingDetails: GetSupportingDataByIdType[] = [
  {
    id: '0',
    propertyName: 'Lumphini Tower',
    developer: 'Lumphini Real Estate Co., Ltd.',
    modelName: null,
    collateralType: '02',
    buildingType: '03',
    landArea: 320,
    usableArea: 18500,
    projectName: 'Lumphini Tower',
    roomFloor: null,
    houseNo: '1168/21',
    subDistrict: 'Lumphini',
    district: 'Pathum Wan',
    province: 'Bangkok',
    latitude: 13.7286,
    longitude: 100.5419,
    plotLocationType: '01',
    pricePerUnit: 280000,
    offeringPrice: 95000000,
    sellingPrice: 89500000,
    phoneNo: '+66-2-252-1111',
    informationDate: '2026-03-12T09:00:00+07:00',
    website: 'https://lumphinitower.example.com',
    sourceUrl: 'https://www.ddproperty.com/listing/lumphini-tower',
    remark: 'Grade-A office tower in CBD, walking distance to MRT Lumphini.',
  },
  {
    id: '1',
    propertyName: 'Silom Complex',
    developer: 'Silom Holdings PLC',
    modelName: null,
    collateralType: '05',
    buildingType: '03',
    landArea: 250,
    usableArea: 22000,
    projectName: 'Silom Complex',
    roomFloor: null,
    houseNo: '191',
    subDistrict: 'Silom',
    district: 'Bang Rak',
    province: 'Bangkok',
    latitude: 13.7286,
    longitude: 100.534,
    plotLocationType: '01',
    pricePerUnit: 250000,
    offeringPrice: 78000000,
    sellingPrice: 75000000,
    phoneNo: '+66-2-231-3500',
    informationDate: '2026-02-20T14:30:00+07:00',
    website: 'https://silomcomplex.example.com',
    sourceUrl: 'https://www.ddproperty.com/listing/silom-complex',
    remark: 'Mixed-use commercial building near BTS Sala Daeng.',
  },
  {
    id: '2',
    propertyName: 'Sukhumvit Garden Residence',
    developer: 'Bangkok Property Development Co., Ltd.',
    modelName: 'Type B - Corner Unit',
    collateralType: '08',
    buildingType: '02',
    landArea: 0,
    usableArea: 65.5,
    projectName: 'Sukhumvit Garden',
    roomFloor: '12',
    houseNo: '22/15',
    subDistrict: 'Khlong Tan Nuea',
    district: 'Watthana',
    province: 'Bangkok',
    latitude: 13.7308,
    longitude: 100.5697,
    plotLocationType: '01',
    pricePerUnit: 125000,
    offeringPrice: 8500000,
    sellingPrice: 8200000,
    phoneNo: '+66-2-123-4567',
    informationDate: '2026-04-15T10:30:00+07:00',
    website: 'https://sukhumvitgarden.example.com',
    sourceUrl: 'https://www.ddproperty.com/listing/sukhumvit-garden-12-65sqm',
    remark: 'Corner unit with city view, fully furnished, near BTS Phrom Phong.',
  },
  {
    id: '3',
    propertyName: 'Asoke Land Plot',
    developer: null,
    modelName: null,
    collateralType: '01',
    buildingType: '00',
    landArea: 180,
    usableArea: null,
    projectName: null,
    roomFloor: null,
    houseNo: '88',
    subDistrict: 'Khlong Toei Nuea',
    district: 'Watthana',
    province: 'Bangkok',
    latitude: 13.7376,
    longitude: 100.5602,
    plotLocationType: '01',
    pricePerUnit: 320000,
    offeringPrice: 65000000,
    sellingPrice: 62000000,
    phoneNo: '+66-81-234-5678',
    informationDate: '2026-01-08T11:15:00+07:00',
    website: null,
    sourceUrl: 'https://www.thaiproperty.com/asoke-land-180',
    remark: 'Vacant plot near Asoke intersection, suitable for high-rise development.',
  },
  {
    id: '4',
    propertyName: 'Sathorn Office Building',
    developer: 'Sathorn Estates Co., Ltd.',
    modelName: null,
    collateralType: '05',
    buildingType: '03',
    landArea: 200,
    usableArea: 15800,
    projectName: 'Sathorn Estates',
    roomFloor: null,
    houseNo: '175/3',
    subDistrict: 'Suriyawong',
    district: 'Bang Rak',
    province: 'Bangkok',
    latitude: 13.7234,
    longitude: 100.5292,
    plotLocationType: '01',
    pricePerUnit: 280000,
    offeringPrice: 72000000,
    sellingPrice: 70000000,
    phoneNo: '+66-2-636-7000',
    informationDate: '2026-03-28T13:00:00+07:00',
    website: 'https://sathornestates.example.com',
    sourceUrl: 'https://www.ddproperty.com/listing/sathorn-office',
    remark: '20-story office building, fully leased, BTS Chong Nonsi nearby.',
  },
  {
    id: '5',
    propertyName: 'Riverside Condominium',
    developer: 'Chao Phraya Living Co.',
    modelName: 'River View 1BR',
    collateralType: '33',
    buildingType: '01',
    landArea: 0,
    usableArea: 48,
    projectName: 'Riverside Residences',
    roomFloor: '24',
    houseNo: '257/45',
    subDistrict: 'Khlong San',
    district: 'Khlong San',
    province: 'Bangkok',
    latitude: 13.7268,
    longitude: 100.5101,
    plotLocationType: '02',
    pricePerUnit: 180000,
    offeringPrice: 9200000,
    sellingPrice: 8800000,
    phoneNo: '+66-2-440-2999',
    informationDate: '2026-04-02T09:45:00+07:00',
    website: 'https://riversideresidences.example.com',
    sourceUrl: 'https://www.ddproperty.com/listing/riverside-condo-24f',
    remark: 'High floor unit, river view, ICONSIAM walking distance.',
  },
  {
    id: '6',
    propertyName: 'Ratchada Land Allocation',
    developer: 'Ratchada Developers PLC',
    modelName: null,
    collateralType: '04',
    buildingType: '00',
    landArea: 1250,
    usableArea: null,
    projectName: 'Ratchada Town Project',
    roomFloor: null,
    houseNo: '120',
    subDistrict: 'Huai Khwang',
    district: 'Huai Khwang',
    province: 'Bangkok',
    latitude: 13.7649,
    longitude: 100.5697,
    plotLocationType: '01',
    pricePerUnit: 220000,
    offeringPrice: 285000000,
    sellingPrice: 275000000,
    phoneNo: '+66-2-694-1000',
    informationDate: '2026-02-05T15:20:00+07:00',
    website: 'https://ratchadadevs.example.com',
    sourceUrl: 'https://www.thaiproperty.com/ratchada-allocation',
    remark: 'Approved land allocation project, 45 plots, MRT Thailand Cultural Centre.',
  },
  {
    id: '7',
    propertyName: 'Pak Kret Townhouse',
    developer: 'Pak Kret Homes Co., Ltd.',
    modelName: '3-Story Townhouse Type C',
    collateralType: '02',
    buildingType: '04',
    landArea: 24,
    usableArea: 180,
    projectName: 'Pak Kret Homes Phase 2',
    roomFloor: null,
    houseNo: '99/12',
    subDistrict: 'Pak Kret',
    district: 'Pak Kret',
    province: 'Nonthaburi',
    latitude: 13.9125,
    longitude: 100.4982,
    plotLocationType: '02',
    pricePerUnit: 95000,
    offeringPrice: 5800000,
    sellingPrice: 5500000,
    phoneNo: '+66-2-583-1200',
    informationDate: '2026-04-10T10:00:00+07:00',
    website: 'https://pakkrethomes.example.com',
    sourceUrl: 'https://www.ddproperty.com/listing/pakkret-th-phase2',
    remark: '3-bedroom townhouse with parking, near Central Chaengwattana.',
  },
  {
    id: '8',
    propertyName: 'Bang Phut Riverside Land',
    developer: null,
    modelName: null,
    collateralType: '01',
    buildingType: '00',
    landArea: 410,
    usableArea: null,
    projectName: null,
    roomFloor: null,
    houseNo: '45/8',
    subDistrict: 'Bang Phut',
    district: 'Pak Kret',
    province: 'Nonthaburi',
    latitude: 13.9075,
    longitude: 100.4944,
    plotLocationType: '03',
    pricePerUnit: 75000,
    offeringPrice: 32500000,
    sellingPrice: 31000000,
    phoneNo: '+66-86-111-2222',
    informationDate: '2026-01-22T08:30:00+07:00',
    website: null,
    sourceUrl: 'https://www.thaiproperty.com/bangphut-river-410',
    remark: 'Riverside vacant land, suitable for resort or private residence.',
  },
  {
    id: '9',
    propertyName: 'Samut Prakan Warehouse',
    developer: 'Industrial Estate Co.',
    modelName: 'Standard Warehouse Type W2',
    collateralType: '05',
    buildingType: '05',
    landArea: 800,
    usableArea: 3200,
    projectName: 'Bangna Industrial Park',
    roomFloor: null,
    houseNo: '333/7',
    subDistrict: 'Bang Krachao',
    district: 'Phra Pradaeng',
    province: 'Samut Prakan',
    latitude: 13.6464,
    longitude: 100.5564,
    plotLocationType: '01',
    pricePerUnit: 45000,
    offeringPrice: 42000000,
    sellingPrice: 40000000,
    phoneNo: '+66-2-385-7700',
    informationDate: '2026-03-05T14:00:00+07:00',
    website: 'https://bangnaindustrial.example.com',
    sourceUrl: 'https://www.industrialproperty.co.th/bangna-w7',
    remark: 'Warehouse with loading docks, 8m ceiling, near Bangna-Trad Highway.',
  },
  {
    id: '10',
    propertyName: 'Pattaya Beach Villa',
    developer: 'Pattaya Villas Group',
    modelName: 'Sea View Villa Type A',
    collateralType: '02',
    buildingType: '01',
    landArea: 120,
    usableArea: 320,
    projectName: 'Pattaya Bay Villas',
    roomFloor: null,
    houseNo: '78/2',
    subDistrict: 'Nong Prue',
    district: 'Bang Lamung',
    province: 'Chonburi',
    latitude: 12.9276,
    longitude: 100.877,
    plotLocationType: '02',
    pricePerUnit: 180000,
    offeringPrice: 28500000,
    sellingPrice: 27500000,
    phoneNo: '+66-38-251-100',
    informationDate: '2026-04-18T11:30:00+07:00',
    website: 'https://pattayabayvillas.example.com',
    sourceUrl: 'https://www.ddproperty.com/listing/pattaya-villa-78-2',
    remark: '4-bedroom villa with private pool, 200m from Jomtien Beach.',
  },
  {
    id: '11',
    propertyName: 'Na Kluea Seaview Condo',
    developer: 'Pattaya Riviera Development',
    modelName: 'Sea View 2BR',
    collateralType: '33',
    buildingType: '01',
    landArea: 0,
    usableArea: 78,
    projectName: 'Riviera Wongamat',
    roomFloor: '18',
    houseNo: '212/108',
    subDistrict: 'Na Kluea',
    district: 'Bang Lamung',
    province: 'Chonburi',
    latitude: 12.9522,
    longitude: 100.8911,
    plotLocationType: '02',
    pricePerUnit: 110000,
    offeringPrice: 9200000,
    sellingPrice: 8800000,
    phoneNo: '+66-38-414-500',
    informationDate: '2026-03-30T13:15:00+07:00',
    website: 'https://rivierawongamat.example.com',
    sourceUrl: 'https://www.ddproperty.com/listing/riviera-wongamat-2br',
    remark: '2-bedroom corner unit, sea view, Wongamat Beach front.',
  },
  {
    id: '12',
    propertyName: 'Chiang Mai Old City House',
    developer: null,
    modelName: null,
    collateralType: '02',
    buildingType: '01',
    landArea: 65,
    usableArea: 220,
    projectName: null,
    roomFloor: null,
    houseNo: '14/3',
    subDistrict: 'Si Phum',
    district: 'Mueang Chiang Mai',
    province: 'Chiang Mai',
    latitude: 18.7889,
    longitude: 98.9844,
    plotLocationType: '02',
    pricePerUnit: 85000,
    offeringPrice: 12500000,
    sellingPrice: 11800000,
    phoneNo: '+66-53-217-800',
    informationDate: '2026-02-12T10:45:00+07:00',
    website: null,
    sourceUrl: 'https://www.ddproperty.com/listing/chiangmai-oldcity-house',
    remark: 'Traditional Lanna-style house, walled garden, inside old city moat.',
  },
  {
    id: '13',
    propertyName: 'Suthep Mountain Plot',
    developer: null,
    modelName: null,
    collateralType: '01',
    buildingType: '00',
    landArea: 580,
    usableArea: null,
    projectName: null,
    roomFloor: null,
    houseNo: '56',
    subDistrict: 'Suthep',
    district: 'Mueang Chiang Mai',
    province: 'Chiang Mai',
    latitude: 18.7969,
    longitude: 98.9489,
    plotLocationType: '03',
    pricePerUnit: 55000,
    offeringPrice: 33000000,
    sellingPrice: 31500000,
    phoneNo: '+66-89-555-1234',
    informationDate: '2026-01-15T09:00:00+07:00',
    website: null,
    sourceUrl: 'https://www.thaiproperty.com/suthep-mountain-580',
    remark: 'Mountain view plot near Doi Suthep, residential zone.',
  },
  {
    id: '14',
    propertyName: 'Patong Beach Hotel',
    developer: 'Phuket Hospitality Group',
    modelName: null,
    collateralType: '07',
    buildingType: '06',
    landArea: 450,
    usableArea: 8500,
    projectName: 'Patong Bay Hotel',
    roomFloor: null,
    houseNo: '88/99',
    subDistrict: 'Pa Tong',
    district: 'Kathu',
    province: 'Phuket',
    latitude: 7.8961,
    longitude: 98.2966,
    plotLocationType: '01',
    pricePerUnit: 165000,
    offeringPrice: 425000000,
    sellingPrice: 410000000,
    phoneNo: '+66-76-340-100',
    informationDate: '2026-03-18T14:30:00+07:00',
    website: 'https://patongbayhotel.example.com',
    sourceUrl: 'https://www.hotelinvest.com/patong-bay-hotel',
    remark: '4-star hotel, 180 keys, 150m from Patong Beach, going concern sale.',
  },
  {
    id: '15',
    propertyName: 'Karon Resort Land',
    developer: null,
    modelName: null,
    collateralType: '01',
    buildingType: '00',
    landArea: 720,
    usableArea: null,
    projectName: null,
    roomFloor: null,
    houseNo: '101/5',
    subDistrict: 'Karon',
    district: 'Mueang Phuket',
    province: 'Phuket',
    latitude: 7.8458,
    longitude: 98.2942,
    plotLocationType: '02',
    pricePerUnit: 95000,
    offeringPrice: 72000000,
    sellingPrice: 68500000,
    phoneNo: '+66-81-789-4444',
    informationDate: '2026-02-28T11:00:00+07:00',
    website: null,
    sourceUrl: 'https://www.thaiproperty.com/karon-resort-720',
    remark: 'Hillside land with sea view, 500m from Karon Beach.',
  },
  {
    id: '16',
    propertyName: 'Rawai Leasehold Estate',
    developer: 'Andaman Residences Co.',
    modelName: 'Pool Villa Type B',
    collateralType: '25',
    buildingType: '01',
    landArea: 90,
    usableArea: 240,
    projectName: 'Andaman Rawai Villas',
    roomFloor: null,
    houseNo: '67/12',
    subDistrict: 'Rawai',
    district: 'Mueang Phuket',
    province: 'Phuket',
    latitude: 7.7758,
    longitude: 98.3275,
    plotLocationType: '02',
    pricePerUnit: 145000,
    offeringPrice: 18500000,
    sellingPrice: 17800000,
    phoneNo: '+66-76-388-200',
    informationDate: '2026-04-05T15:00:00+07:00',
    website: 'https://andamanrawai.example.com',
    sourceUrl: 'https://www.ddproperty.com/listing/andaman-rawai-villa',
    remark: '30-year leasehold pool villa, 3BR, near Rawai Beach pier.',
  },
  {
    id: '17',
    propertyName: 'Bangkok Logistics Truck Fleet',
    developer: null,
    modelName: 'Hino 500 Series FM2P',
    collateralType: '10',
    buildingType: '00',
    landArea: null,
    usableArea: null,
    projectName: null,
    roomFloor: null,
    houseNo: '999/1',
    subDistrict: 'Khlong Sam Prawet',
    district: 'Lat Krabang',
    province: 'Bangkok',
    latitude: 13.6904,
    longitude: 100.7501,
    plotLocationType: null,
    pricePerUnit: 2500000,
    offeringPrice: 12500000,
    sellingPrice: 11800000,
    phoneNo: '+66-2-326-7777',
    informationDate: '2026-04-22T09:30:00+07:00',
    website: null,
    sourceUrl: 'https://www.truck2hand.com/listing/hino-fleet-5',
    remark: 'Fleet of 5 trucks, 2023 models, well-maintained, full service history.',
  },
  {
    id: '18',
    propertyName: 'Industrial CNC Machinery',
    developer: null,
    modelName: 'Mazak Integrex i-200',
    collateralType: '11',
    buildingType: '00',
    landArea: null,
    usableArea: null,
    projectName: null,
    roomFloor: null,
    houseNo: '444/22',
    subDistrict: 'Bang Pu Mai',
    district: 'Mueang Samut Prakan',
    province: 'Samut Prakan',
    latitude: 13.6464,
    longitude: 100.7032,
    plotLocationType: null,
    pricePerUnit: 8500000,
    offeringPrice: 8500000,
    sellingPrice: 8200000,
    phoneNo: '+66-2-709-3000',
    informationDate: '2026-03-25T10:15:00+07:00',
    website: null,
    sourceUrl: 'https://www.machinetools.co.th/listing/mazak-i200',
    remark: '5-axis CNC machining center, 2022 model, 2,400 hours.',
  },
  {
    id: '19',
    propertyName: 'Chao Phraya Cargo Vessel',
    developer: null,
    modelName: 'Cargo Barge 500-ton',
    collateralType: '12',
    buildingType: '00',
    landArea: null,
    usableArea: null,
    projectName: null,
    roomFloor: null,
    houseNo: '5',
    subDistrict: 'Tha Chin',
    district: 'Mueang Samut Sakhon',
    province: 'Samut Sakhon',
    latitude: 13.599,
    longitude: 100.5436,
    plotLocationType: null,
    pricePerUnit: 25000000,
    offeringPrice: 25000000,
    sellingPrice: 23500000,
    phoneNo: '+66-34-411-500',
    informationDate: '2026-02-08T13:45:00+07:00',
    website: null,
    sourceUrl: 'https://www.thaimarine.com/cargo-barge-500',
    remark: '500-ton cargo barge, Thai-flagged, active commercial certification.',
  },
];
