import type { ListBoxItem } from '@/shared/components';

export const companies: ListBoxItem[] = [
  { value: '01', label: 'Company A', id: '', isActive: true },
  { value: '02', label: 'Company B', id: '', isActive: true },
  { value: '03', label: 'Company C', id: '', isActive: true },
  { value: '04', label: 'Company D', id: '', isActive: true },
];

export const collateralTypeOptions: { value: string; label: string }[] = [
  { value: '01', label: 'Land' },
  { value: '02', label: 'Land with buildings' },
  { value: '03', label: 'Land with buildings (blueprint)' },
  { value: '04', label: 'Land allocation (whole project)' },
  { value: '05', label: 'Buildings' },
  { value: '06', label: 'Building (blueprint)' },
  { value: '07', label: 'Building (whole project)' },
  { value: '08', label: 'Apartment' },
  { value: '09', label: 'Leasehold rights, real estate' },
  { value: '10', label: 'Car' },
  { value: '11', label: 'Machinery' },
  { value: '12', label: 'Ship' },
  { value: '13', label: 'Land (Part 1)' },
  { value: '14', label: 'Land (Part 2)' },
  { value: '15', label: 'Building (Part 1)' },
  { value: '16', label: 'Building (Part 2)' },
  { value: '17', label: 'Land (Part 2)' },
  { value: '18', label: 'Building (Part 2)' },
  { value: '19', label: 'Land (Group 1)' },
  { value: '20', label: 'Building (Group 1)' },
  { value: '21', label: 'Land (Group 2)' },
  { value: '22', label: 'Building (Group 2)' },
  { value: '23', label: 'Land with buildings (Group 1)' },
  { value: '24', label: 'Land with buildings (Group 2)' },
  { value: '25', label: 'Leasehold rights (land with buildings)' },
  { value: '26', label: 'Land (Group 3)' },
  { value: '27', label: 'Land (Group 4)' },
  { value: '28', label: 'Leasehold rights (condominium)' },
  { value: '29', label: 'Land lease rights' },
  { value: '30', label: 'Leasehold rights' },
  { value: '31', label: 'Lease rights for space within shopping center' },
  { value: '32', label: 'Land with buildings (BlockLand)' },
  { value: '33', label: 'Condominium (BlockCondo)' },
];
