import { z } from 'zod';

const landTitleItem = z.object({
  titleNumber: z.string(),
  titleType: z.string(),
  bookNumber: z.string().nullable().optional(),
  pageNumber: z.string().nullable().optional(),
  landParcelNumber: z.string().nullable().optional(),
  surveyNumber: z.string().nullable().optional(),
  mapSheetNumber: z.string().nullable().optional(),
  rawang: z.string().nullable().optional(),
  aerialMapName: z.string().nullable().optional(),
  aerialMapNumber: z.string().nullable().optional(),
  rai: z.number().nullable().optional(),
  ngan: z.number().nullable().optional(),
  squareWa: z.number().nullable().optional(),
  hasBoundaryMarker: z.boolean().nullable().optional(),
  boundaryMarkerRemark: z.string().nullable().optional(),
  isDocumentValidated: z.boolean().nullable().optional(),
  isMissingFromSurvey: z.boolean().nullable().optional(),
  governmentPricePerSqWa: z.number().nullable().optional(),
  governmentPrice: z.number().nullable().optional(),
  remark: z.string().nullable().optional(),
});

export const createLandForm = z.object({
  titles: z.array(landTitleItem).nullable().optional(),
  propertyName: z.string().nullable().optional(),
  latitude: z.coerce.number(),
  longitude: z.coerce.number(),
  subDistrict: z.string().min(1, 'Sub district is required.'),
  subDistrictName: z.string().nullable(),
  district: z.string().min(1, 'District is required.'),
  districtName: z.string().nullable(),
  province: z.string().min(1, 'Province is required.'),
  provinceName: z.string().nullable(),
  landOffice: z.string().min(1, 'Land office is required.'),
  landDescription: z.string().min(1, 'Land description is required.'),
  isOwnerVerified: z.boolean(),
  ownerName: z.string(),
  hasObligation: z.boolean(),
  obligationDetails: z.string(),
  isLandLocationVerified: z.boolean(),
  landCheckMethodType: z.string().nullable().optional(),
  landCheckMethodTypeOther: z.string().nullable().optional(),
  street: z.string().min(1, 'Street is required.'),
  soi: z.string().nullable().optional(),
  distanceFromMainRoad: z.coerce.number().nullable().optional(),
  village: z.string().nullable().optional(),
  addressLocation: z.string().nullable().optional(),
  landShapeType: z.string().nullable().optional(),
  urbanPlanningType: z.string().nullable().optional(),
  landZoneType: z.array(z.string()).nullable().optional(),
  plotLocationType: z.array(z.string()).nullable().optional(),
  plotLocationTypeOther: z.string().nullable().optional(),
  landFillType: z.string().nullable().optional(),
  landFillTypeOther: z.string().nullable().optional(),
  landFillPercent: z.coerce.number().nullable().optional(),
  soilLevel: z.coerce.number().nullable().optional(),
  accessRoadWidth: z.coerce.number().nullable().optional(),
  rightOfWay: z.coerce.number().nullable().optional(),
  roadFrontage: z.coerce.number().nullable().optional(),
  numberOfSidesFacingRoad: z.coerce.number().nullable().optional(),
  roadPassInFrontOfLand: z.string().nullable().optional(),
  landAccessibilityType: z.string().nullable().optional(),
  landAccessibilityRemark: z.string().nullable().optional(),
  roadSurfaceType: z.string().nullable().optional(),
  roadSurfaceTypeOther: z.string().nullable().optional(),
  publicUtilityType: z.array(z.string()).nullable().optional(),
  publicUtilityTypeOther: z.string().nullable().optional(),
  landUseType: z.array(z.string()).nullable().optional(),
  landUseTypeOther: z.string().nullable().optional(),
  landEntranceExitType: z.array(z.string()).nullable().optional(),
  landEntranceExitTypeOther: z.string().nullable().optional(),
  transportationAccessType: z.array(z.string()).nullable().optional(),
  transportationAccessTypeOther: z.string().nullable().optional(),
  propertyAnticipationType: z.string().nullable().optional(),
  isExpropriated: z.boolean(),
  expropriationRemark: z.string().nullable().optional(),
  isInExpropriationLine: z.boolean().nullable().optional(),
  expropriationLineRemark: z.string().nullable().optional(),
  royalDecree: z.string().nullable().optional(),
  isEncroached: z.boolean(),
  encroachmentRemark: z.string().nullable().optional(),
  encroachmentArea: z.coerce.number().nullable().optional(),
  hasElectricity: z.boolean(),
  electricityDistance: z.coerce.number().nullable().optional(),
  isLandlocked: z.boolean(),
  landlockedRemark: z.string().nullable().optional(),
  isForestBoundary: z.boolean(),
  forestBoundaryRemark: z.string().nullable().optional(),
  otherLegalLimitations: z.string().nullable().optional(),
  evictionType: z.array(z.string()).nullable().optional(),
  evictionTypeOther: z.string().nullable().optional(),
  allocationType: z.string().nullable().optional(),
  northAdjacentArea: z.string().nullable().optional(),
  northBoundaryLength: z.coerce.number().nullable().optional(),
  southAdjacentArea: z.string().nullable().optional(),
  southBoundaryLength: z.coerce.number().nullable().optional(),
  eastAdjacentArea: z.string().nullable().optional(),
  eastBoundaryLength: z.coerce.number().nullable().optional(),
  westAdjacentArea: z.string().nullable().optional(),
  westBoundaryLength: z.coerce.number().nullable().optional(),
  pondArea: z.coerce.number().nullable().optional(),
  pondDepth: z.coerce.number().nullable().optional(),
  hasBuilding: z.boolean(),
  hasBuildingOther: z.string().nullable().optional(),
  remark: z.string().nullable().optional(),
});

export const createBuildingForm = z.object({
  ownerName: z.string().min(1, 'Owner name is required.'),
  propertyName: z.string().nullable(),
  buildingNumber: z.string().min(1, 'Building number is required.'),
  modelName: z.string().min(1, 'Model name is required.'),
  builtOnTitleNumber: z.string().min(1, 'Built on title number is required.'),
  isOwnerVerified: z.boolean(),
  houseNumber: z.string().min(1, 'House number is required.'),
  buildingConditionType: z.string(),
  isUnderConstruction: z.boolean(),
  constructionCompletionPercent: z.coerce.number(),
  constructionLicenseExpirationDate: z.string().datetime({ offset: true }),
  isAppraisable: z.boolean(),
  hasObligation: z.boolean(),
  obligationDetails: z.string(),
  buildingType: z.string().nullable(),
  buildingTypeOther: z.string().nullable(),
  numberOfFloors: z.coerce.number(),
  decorationType: z.string(),
  decorationTypeOther: z.string().nullable(),
  isEncroachingOthers: z.boolean(),
  encroachingOthersRemark: z.string().nullable(),
  encroachingOthersArea: z.coerce.number().nullable(),
  buildingMaterialType: z.string().nullable(),
  buildingStyleType: z.string().nullable(),
  isResidential: z.boolean(),
  buildingAge: z.coerce.number(),
  residentialRemark: z.string().nullable(),
  constructionStyleRemark: z.string().nullable(),
  constructionStyleType: z.string().nullable(),
  structureType: z.array(z.string()).nullable(),
  structureTypeOther: z.string().nullable(),
  roofFrameType: z.array(z.string()).nullable(),
  roofFrameTypeOther: z.string().nullable(),
  roofType: z.array(z.string()).nullable(),
  roofTypeOther: z.string().nullable(),
  ceilingType: z.array(z.string()).nullable(),
  ceilingTypeOther: z.string().nullable(),
  interiorWallType: z.array(z.string()).nullable(),
  interiorWallTypeOther: z.string().nullable(),
  exteriorWallType: z.array(z.string()).nullable(),
  exteriorWallTypeOther: z.string().nullable(),
  fenceType: z.array(z.string()).nullable(),
  fenceTypeOther: z.string().nullable(),
  constructionType: z.string().nullable(),
  constructionTypeOther: z.string().nullable(),
  utilizationType: z.string().nullable(),
  utilizationTypeOther: z.string().nullable(),
  totalBuildingArea: z.coerce.number(),
  buildingInsurancePrice: z.coerce.number().nullable(),
  sellingPrice: z.coerce.number().nullable(),
  forcedSalePrice: z.coerce.number().nullable(),
  remark: z.string().nullable(),
});

const AreaDetailDto = z
  .object({
    id: z.string().uuid().nullable(),
    areaDescription: z.string().nullable(),
    areaSize: z.coerce.number().nullable(),
  })
  .passthrough();

export const createCondoForm = z.object({
  ownerName: z.string().min(1, 'Owner name is required.'),

  propertyName: z.string(),
  condoName: z.string().min(1, 'Condo name is required.'),
  buildingNumber: z.string().min(1, 'Building number is required.'),
  modelName: z.string().min(1, 'Model name is required.'),
  builtOnTitleNumber: z.string().min(1, 'Built on title number is required.'),
  condoRegistrationNumber: z.string().min(1, 'Condo registration number is required.'),
  roomNumber: z.string().min(1, 'Room number is required.'),
  floorNumber: z.coerce.number(),
  usableArea: z.coerce.number(),

  latitude: z.coerce.number(),
  longitude: z.coerce.number(),

  subDistrict: z.string().min(1, 'Sub district is required.'),
  district: z.string().min(1, 'District is required.'),
  province: z.string().min(1, 'Province is required.'),
  landOffice: z.string().min(1, 'Land office is required.'),

  isOwnerVerified: z.boolean(),
  buildingConditionType: z.string(),
  hasObligation: z.boolean(),
  obligationDetails: z.string(),
  isDocumentValidated: z.boolean(),

  locationType: z.string().nullable(),
  street: z.string().nullable(),
  soi: z.string().nullable(),
  distanceFromMainRoad: z.coerce.number().nullable(),
  accessRoadWidth: z.coerce.number().nullable(),
  rightOfWay: z.coerce.number().nullable(),
  roadSurfaceType: z.string().nullable(),
  publicUtilityType: z.array(z.string()).nullable(),
  publicUtilityTypeOther: z.string().nullable(),

  decorationType: z.string(),
  decorationTypeOther: z.string().nullable(),
  buildingAge: z.coerce.number(),
  numberOfFloors: z.coerce.number(),
  buildingFormType: z.string().nullable(),
  constructionMaterialType: z.string().nullable(),

  roomLayoutType: z.string().nullable(),
  roomLayoutTypeOther: z.string().nullable(),
  locationViewType: z.array(z.string()).nullable(),
  groundFloorMaterialType: z.string().nullable(),
  groundFloorMaterialTypeOther: z.string().nullable(),
  upperFloorMaterialType: z.string().nullable(),
  upperFloorMaterialTypeOther: z.string().nullable(),
  bathroomFloorMaterialType: z.string().nullable(),
  bathroomFloorMaterialTypeOther: z.string().nullable(),
  roofType: z.string().nullable(),
  roofTypeOther: z.string().nullable(),

  areaDetails: z.array(AreaDetailDto).nullable(),
  totalBuildingArea: z.coerce.number(),

  isExpropriated: z.boolean(),
  expropriationRemark: z.string().nullable(),
  isInExpropriationLine: z.boolean(),
  expropriationLineRemark: z.string().nullable(),
  royalDecree: z.string().nullable(),
  isForestBoundary: z.boolean(),
  forestBoundaryRemark: z.string().nullable(),

  facilityType: z.array(z.string()).nullable(),
  facilityTypeOther: z.string().nullable(),
  environmentType: z.array(z.string()).nullable(),

  buildingInsurancePrice: z.coerce.number().nullable(),
  sellingPrice: z.coerce.number().nullable(),
  forcedSalePrice: z.coerce.number().nullable(),

  remark: z.string().nullable(),
});

export const createLandAndBuildingForm = z.object({
  titles: z.array(landTitleItem).nullable().optional(),
  propertyName: z.string().nullable().optional(),
  latitude: z.coerce.number(),
  longitude: z.coerce.number(),
  subDistrict: z.string().min(1, 'Sub district is required.'),
  subDistrictName: z.string().nullable(),
  district: z.string().min(1, 'District is required.'),
  districtName: z.string().nullable(),
  province: z.string().min(1, 'Province is required.'),
  provinceName: z.string().nullable(),
  landOffice: z.string().min(1, 'Land office is required.'),
  landDescription: z.string().min(1, 'Land description is required.'),
  isOwnerVerified: z.boolean(),
  ownerName: z.string(),
  hasObligation: z.boolean(),
  obligationDetails: z.string(),
  isLandLocationVerified: z.boolean(),
  landCheckMethodType: z.string().nullable().optional(),
  landCheckMethodTypeOther: z.string().nullable().optional(),
  street: z.string().min(1, 'Street is required.'),
  soi: z.string().nullable().optional(),
  distanceFromMainRoad: z.coerce.number().nullable().optional(),
  village: z.string().nullable().optional(),
  addressLocation: z.string().nullable().optional(),
  landShapeType: z.string().nullable().optional(),
  urbanPlanningType: z.string().nullable().optional(),
  landZoneType: z.array(z.string()).nullable().optional(),
  plotLocationType: z.array(z.string()).nullable().optional(),
  plotLocationTypeOther: z.string().nullable().optional(),
  landFillType: z.string().nullable().optional(),
  landFillTypeOther: z.string().nullable().optional(),
  landFillPercent: z.coerce.number().nullable().optional(),
  soilLevel: z.coerce.number().nullable().optional(),
  accessRoadWidth: z.coerce.number().nullable().optional(),
  rightOfWay: z.coerce.number().nullable().optional(),
  roadFrontage: z.coerce.number().nullable().optional(),
  numberOfSidesFacingRoad: z.coerce.number().nullable().optional(),
  roadPassInFrontOfLand: z.string().nullable().optional(),
  landAccessibilityType: z.string().nullable().optional(),
  landAccessibilityRemark: z.string().nullable().optional(),
  roadSurfaceType: z.string().nullable().optional(),
  roadSurfaceTypeOther: z.string().nullable().optional(),
  publicUtilityType: z.array(z.string()).nullable().optional(),
  publicUtilityTypeOther: z.string().nullable().optional(),
  landUseType: z.array(z.string()).nullable().optional(),
  landUseTypeOther: z.string().nullable().optional(),
  landEntranceExitType: z.array(z.string()).nullable().optional(),
  landEntranceExitTypeOther: z.string().nullable().optional(),
  transportationAccessType: z.array(z.string()).nullable().optional(),
  transportationAccessTypeOther: z.string().nullable().optional(),
  propertyAnticipationType: z.string().nullable().optional(),
  isExpropriated: z.boolean(),
  expropriationRemark: z.string().nullable().optional(),
  isInExpropriationLine: z.boolean().nullable().optional(),
  expropriationLineRemark: z.string().nullable().optional(),
  royalDecree: z.string().nullable().optional(),
  isEncroached: z.boolean(),
  encroachmentRemark: z.string().nullable().optional(),
  encroachmentArea: z.coerce.number().nullable().optional(),
  hasElectricity: z.boolean(),
  electricityDistance: z.coerce.number().nullable().optional(),
  isLandlocked: z.boolean(),
  landlockedRemark: z.string().nullable().optional(),
  isForestBoundary: z.boolean(),
  forestBoundaryRemark: z.string().nullable().optional(),
  otherLegalLimitations: z.string().nullable().optional(),
  evictionType: z.array(z.string()).nullable().optional(),
  evictionTypeOther: z.string().nullable().optional(),
  allocationType: z.string().nullable().optional(),
  northAdjacentArea: z.string().nullable().optional(),
  northBoundaryLength: z.coerce.number().nullable().optional(),
  southAdjacentArea: z.string().nullable().optional(),
  southBoundaryLength: z.coerce.number().nullable().optional(),
  eastAdjacentArea: z.string().nullable().optional(),
  eastBoundaryLength: z.coerce.number().nullable().optional(),
  westAdjacentArea: z.string().nullable().optional(),
  westBoundaryLength: z.coerce.number().nullable().optional(),
  pondArea: z.coerce.number().nullable().optional(),
  pondDepth: z.coerce.number().nullable().optional(),
  //Building
  buildingNumber: z.string().min(1, 'Building number is required.'),
  modelName: z.string().min(1, 'Model name is required.'),
  builtOnTitleNumber: z.string().min(1, 'Built on title number is required.'),
  houseNumber: z.string().min(1, 'House number is required.'),
  buildingConditionType: z.string(),
  isUnderConstruction: z.boolean(),
  constructionCompletionPercent: z.coerce.number(),
  constructionLicenseExpirationDate: z.string().datetime({ offset: true }),
  isAppraisable: z.boolean(),
  buildingType: z.string().nullable(),
  buildingTypeOther: z.string().nullable(),
  numberOfFloors: z.coerce.number(),
  decorationType: z.string(),
  decorationTypeOther: z.string().nullable(),
  isEncroachingOthers: z.boolean(),
  encroachingOthersRemark: z.string().nullable(),
  encroachingOthersArea: z.coerce.number().nullable(),
  buildingMaterialType: z.string().nullable(),
  buildingStyleType: z.string().nullable(),
  isResidential: z.boolean(),
  buildingAge: z.coerce.number(),
  residentialRemark: z.string().nullable(),
  constructionStyleRemark: z.string().nullable(),
  constructionStyleType: z.string().nullable(),
  structureType: z.array(z.string()).nullable(),
  structureTypeOther: z.string().nullable(),
  roofFrameType: z.array(z.string()).nullable(),
  roofFrameTypeOther: z.string().nullable(),
  roofType: z.array(z.string()).nullable(),
  roofTypeOther: z.string().nullable(),
  ceilingType: z.array(z.string()).nullable(),
  ceilingTypeOther: z.string().nullable(),
  interiorWallType: z.array(z.string()).nullable(),
  interiorWallTypeOther: z.string().nullable(),
  exteriorWallType: z.array(z.string()).nullable(),
  exteriorWallTypeOther: z.string().nullable(),
  fenceType: z.array(z.string()).nullable(),
  fenceTypeOther: z.string().nullable(),
  constructionType: z.string().nullable(),
  constructionTypeOther: z.string().nullable(),
  utilizationType: z.string().nullable(),
  utilizationTypeOther: z.string().nullable(),
  totalBuildingArea: z.coerce.number(),
  buildingInsurancePrice: z.coerce.number().nullable(),
  sellingPrice: z.coerce.number().nullable(),
  forcedSalePrice: z.coerce.number().nullable(),
  remark: z.string().nullable(),
});

export const landAndBuildingPMAForm = z.object({
  buildingInsurancePrice: z.coerce.number().nullable(),
  sellingPrice: z.coerce.number().nullable(),
  forcedSalePrice: z.coerce.number().nullable(),
  titleNo: z.string().nullable().optional(),
  rawang: z.string().nullable().optional(),
  landNo: z.string().nullable().optional(),
  surveyNo: z.string().nullable().optional(),
  bookNumber: z.string().nullable().optional(),
  pageNumber: z.string().nullable().optional(),
  areaRai: z.number().int().nullable().optional(),
  areaNgan: z.number().int().nullable().optional(),
  areaSquareWa: z.number().nullable().optional(),
  subDistrict: z.string().min(1, 'Sub district is required.'),
  subDistrictName: z.string().nullable(),
  district: z.string().min(1, 'District is required.'),
  districtName: z.string().nullable(),
  province: z.string().min(1, 'Province is required.'),
  provinceName: z.string().nullable(),
});

export const condoPMAForm = z.object({
  buildingInsurancePrice: z.coerce.number().nullable(),
  sellingPrice: z.coerce.number().nullable(),
  forcedSalePrice: z.coerce.number().nullable(),
  builtOnTitleNumber: z.string().min(1, 'Built on title number is required.'),
  condoRegistrationNumber: z.string().min(1, 'Condo registration number is required.'),
  roomNumber: z.string().min(1, 'Room number is required.'),
  floorNumber: z.coerce.number(),
  buildingNumber: z.string().min(1, 'Building number is required.'),
  condoName: z.string().min(1, 'Condo name is required.'),
  subDistrict: z.string().min(1, 'Sub district is required.'),
  subDistrictName: z.string().nullable(),
  district: z.string().min(1, 'District is required.'),
  districtName: z.string().nullable(),
  province: z.string().min(1, 'Province is required.'),
  provinceName: z.string().nullable(),
});

export type createCondoFormType = z.infer<typeof createCondoForm>;
export type createBuildingFormType = z.infer<typeof createBuildingForm>;
export type createLandFormType = z.infer<typeof createLandForm>;
export type createLandAndBuildingFormType = z.infer<typeof createLandAndBuildingForm>;
export type landAndBuildingPMAFormType = z.infer<typeof landAndBuildingPMAForm>;
export type condoPMAFormType = z.infer<typeof condoPMAForm>;

//===============================================================

export const createLandFormDefault: createLandFormType = {
  titles: [],
  propertyName: '',
  latitude: 0,
  longitude: 0,
  subDistrict: '',
  subDistrictName: '',
  district: '',
  districtName: '',
  province: '',
  provinceName: '',
  landOffice: '',
  landDescription: '',
  isOwnerVerified: false,
  ownerName: '',
  hasObligation: false,
  obligationDetails: '',
  isLandLocationVerified: false,
  landCheckMethodType: '',
  landCheckMethodTypeOther: '',
  street: '',
  soi: '',
  distanceFromMainRoad: 0,
  village: '',
  addressLocation: '',
  landShapeType: '',
  urbanPlanningType: '',
  landZoneType: [],
  plotLocationType: [],
  plotLocationTypeOther: '',
  landFillType: '',
  landFillTypeOther: '',
  landFillPercent: 0,
  soilLevel: 0,
  accessRoadWidth: 0,
  rightOfWay: 0,
  roadFrontage: 0,
  numberOfSidesFacingRoad: 0,
  roadPassInFrontOfLand: '',
  landAccessibilityType: '',
  landAccessibilityRemark: '',
  roadSurfaceType: '',
  roadSurfaceTypeOther: '',
  publicUtilityType: [],
  publicUtilityTypeOther: '',
  landUseType: [],
  landUseTypeOther: '',
  landEntranceExitType: [],
  landEntranceExitTypeOther: '',
  transportationAccessType: [],
  transportationAccessTypeOther: '',
  propertyAnticipationType: '',
  isExpropriated: false,
  expropriationRemark: '',
  isInExpropriationLine: false,
  expropriationLineRemark: '',
  royalDecree: '',
  isEncroached: false,
  encroachmentRemark: '',
  encroachmentArea: 0,
  hasElectricity: false,
  electricityDistance: 0,
  isLandlocked: false,
  landlockedRemark: '',
  isForestBoundary: false,
  forestBoundaryRemark: '',
  otherLegalLimitations: '',
  evictionType: [],
  evictionTypeOther: '',
  allocationType: '',
  northAdjacentArea: '',
  northBoundaryLength: 0,
  southAdjacentArea: '',
  southBoundaryLength: 0,
  eastAdjacentArea: '',
  eastBoundaryLength: 0,
  westAdjacentArea: '',
  westBoundaryLength: 0,
  pondArea: 0,
  pondDepth: 0,
  hasBuilding: false,
  hasBuildingOther: '',
  remark: '',
};

export const createBuildingFormDefault: createBuildingFormType = {
  ownerName: '',
  propertyName: '',
  buildingNumber: '',
  modelName: '',
  builtOnTitleNumber: '',
  isOwnerVerified: false,
  houseNumber: '',
  buildingConditionType: '',
  isUnderConstruction: false,
  constructionCompletionPercent: 100,
  constructionLicenseExpirationDate: '',
  isAppraisable: false,
  hasObligation: false,
  obligationDetails: '',
  buildingType: '',
  buildingTypeOther: '',
  numberOfFloors: 0,
  decorationType: '',
  decorationTypeOther: '',
  isEncroachingOthers: false,
  encroachingOthersRemark: '',
  encroachingOthersArea: 0,
  buildingMaterialType: '',
  buildingStyleType: '',
  isResidential: true,
  buildingAge: 0,
  residentialRemark: '',
  constructionStyleRemark: '',
  constructionStyleType: '',
  structureType: [],
  structureTypeOther: '',
  roofFrameType: [],
  roofFrameTypeOther: '',
  roofType: [],
  roofTypeOther: '',
  ceilingType: [],
  ceilingTypeOther: '',
  interiorWallType: [],
  interiorWallTypeOther: '',
  exteriorWallType: [],
  exteriorWallTypeOther: '',
  fenceType: [],
  fenceTypeOther: '',
  constructionType: '',
  constructionTypeOther: '',
  utilizationType: '',
  utilizationTypeOther: '',
  totalBuildingArea: 0,
  buildingInsurancePrice: 0,
  sellingPrice: 0,
  forcedSalePrice: 0,
  remark: '',
};

export const createCondoFormDefault: createCondoFormType = {
  ownerName: '',
  propertyName: '',
  condoName: '',
  buildingNumber: '',
  modelName: '',
  builtOnTitleNumber: '',
  condoRegistrationNumber: '',
  roomNumber: '',
  floorNumber: 0,
  usableArea: 0,
  latitude: 0,
  longitude: 0,
  subDistrict: '',
  district: '',
  province: '',
  landOffice: '',
  isOwnerVerified: false,
  buildingConditionType: '',
  hasObligation: false,
  obligationDetails: '',
  isDocumentValidated: true,
  locationType: '',
  street: '',
  soi: '',
  distanceFromMainRoad: 0,
  accessRoadWidth: 0,
  rightOfWay: 0,
  roadSurfaceType: '',
  publicUtilityType: [],
  publicUtilityTypeOther: '',
  decorationType: '',
  decorationTypeOther: '',
  buildingAge: 0,
  numberOfFloors: 0,
  buildingFormType: '',
  constructionMaterialType: '',
  roomLayoutType: '',
  roomLayoutTypeOther: '',
  locationViewType: [],
  groundFloorMaterialType: '',
  groundFloorMaterialTypeOther: '',
  upperFloorMaterialType: '',
  upperFloorMaterialTypeOther: '',
  bathroomFloorMaterialType: '',
  bathroomFloorMaterialTypeOther: '',
  roofType: '',
  roofTypeOther: '',
  areaDetails: [],
  totalBuildingArea: 0,
  isExpropriated: false,
  expropriationRemark: '',
  isInExpropriationLine: false,
  expropriationLineRemark: '',
  royalDecree: '',
  isForestBoundary: false,
  forestBoundaryRemark: '',
  facilityType: [],
  facilityTypeOther: '',
  environmentType: [],
  buildingInsurancePrice: 0,
  sellingPrice: 0,
  forcedSalePrice: 0,
  remark: '',
};

export const createLandAndBuildingFormDefault: createLandAndBuildingFormType = {
  titles: [],
  propertyName: '',
  latitude: 0,
  longitude: 0,
  subDistrict: '',
  subDistrictName: '',
  district: '',
  districtName: '',
  province: '',
  provinceName: '',
  landOffice: '',
  landDescription: '',
  isOwnerVerified: false,
  ownerName: '',
  hasObligation: false,
  obligationDetails: '',
  isLandLocationVerified: false,
  landCheckMethodType: '',
  landCheckMethodTypeOther: '',
  street: '',
  soi: '',
  distanceFromMainRoad: 0,
  village: '',
  addressLocation: '',
  landShapeType: '',
  urbanPlanningType: '',
  landZoneType: [],
  plotLocationType: [],
  plotLocationTypeOther: '',
  landFillType: '',
  landFillTypeOther: '',
  landFillPercent: 0,
  soilLevel: 0,
  accessRoadWidth: 0,
  rightOfWay: 0,
  roadFrontage: 0,
  numberOfSidesFacingRoad: 0,
  roadPassInFrontOfLand: '',
  landAccessibilityType: '',
  landAccessibilityRemark: '',
  roadSurfaceType: '',
  roadSurfaceTypeOther: '',
  publicUtilityType: [],
  publicUtilityTypeOther: '',
  landUseType: [],
  landUseTypeOther: '',
  landEntranceExitType: [],
  landEntranceExitTypeOther: '',
  transportationAccessType: [],
  transportationAccessTypeOther: '',
  propertyAnticipationType: '',
  isExpropriated: false,
  expropriationRemark: '',
  isInExpropriationLine: false,
  expropriationLineRemark: '',
  royalDecree: '',
  isEncroached: false,
  encroachmentRemark: '',
  encroachmentArea: 0,
  hasElectricity: false,
  electricityDistance: 0,
  isLandlocked: false,
  landlockedRemark: '',
  isForestBoundary: false,
  forestBoundaryRemark: '',
  otherLegalLimitations: '',
  evictionType: [],
  evictionTypeOther: '',
  allocationType: '',
  northAdjacentArea: '',
  northBoundaryLength: 0,
  southAdjacentArea: '',
  southBoundaryLength: 0,
  eastAdjacentArea: '',
  eastBoundaryLength: 0,
  westAdjacentArea: '',
  westBoundaryLength: 0,
  pondArea: 0,
  pondDepth: 0,

  //Building
  buildingNumber: '',
  modelName: '',
  builtOnTitleNumber: '',
  houseNumber: '',
  buildingConditionType: '',
  isUnderConstruction: false,
  constructionCompletionPercent: 100,
  constructionLicenseExpirationDate: '',
  isAppraisable: false,
  buildingType: '',
  buildingTypeOther: '',
  numberOfFloors: 0,
  decorationType: '',
  decorationTypeOther: '',
  isEncroachingOthers: false,
  encroachingOthersRemark: '',
  encroachingOthersArea: 0,
  buildingMaterialType: '',
  buildingStyleType: '',
  isResidential: true,
  buildingAge: 0,
  residentialRemark: '',
  constructionStyleRemark: '',
  constructionStyleType: '',
  structureType: [],
  structureTypeOther: '',
  roofFrameType: [],
  roofFrameTypeOther: '',
  roofType: [],
  roofTypeOther: '',
  ceilingType: [],
  ceilingTypeOther: '',
  interiorWallType: [],
  interiorWallTypeOther: '',
  exteriorWallType: [],
  exteriorWallTypeOther: '',
  fenceType: [],
  fenceTypeOther: '',
  constructionType: '',
  constructionTypeOther: '',
  utilizationType: '',
  utilizationTypeOther: '',
  totalBuildingArea: 0,
  buildingInsurancePrice: 0,
  sellingPrice: 0,
  forcedSalePrice: 0,
  remark: '',
};

export const landAndBuildingPMAFormDefault: landAndBuildingPMAFormType = {
  buildingInsurancePrice: 0,
  sellingPrice: 0,
  forcedSalePrice: 0,
  titleNo: '',
  rawang: '',
  landNo: '',
  surveyNo: '',
  bookNumber: '',
  pageNumber: '',
  areaRai: 0,
  areaNgan: 0,
  areaSquareWa: 0,
  subDistrict: '',
  subDistrictName: '',
  district: '',
  districtName: '',
  province: '',
  provinceName: '',
};

export const condoPMAFormDefault: condoPMAFormType = {
  buildingInsurancePrice: 0,
  sellingPrice: 0,
  forcedSalePrice: 0,
  builtOnTitleNumber: '',
  condoRegistrationNumber: '',
  roomNumber: '',
  floorNumber: 0,
  buildingNumber: '',
  condoName: '',
  subDistrict: '',
  subDistrictName: '',
  district: '',
  districtName: '',
  province: '',
  provinceName: '',
};
