import { buildFormSchema } from '@/shared/components/form/schemaBuilder';
import { z } from 'zod';
import {
  allBuildingFields,
  allCondoFields,
  allLandBuildingFields,
  allLandFields,
} from '../configs/fields';

const landTitleItem = z.object({
  titleNumber: z.string(),
  titleType: z.string(),
  bookNumber: z.string().nullable().optional(),
  pageNumber: z.string().nullable().optional(),
  landParcelNumber: z.string().nullable().optional(),
  surveyNumber: z.string().nullable().optional(),
  mapSheetNumber: z.string().nullable().optional(),
  rawang: z.string().nullable().optional(),
  aerialMapName: z.string().nullable().optional(),
  aerialMapNumber: z.string().nullable().optional(),
  rai: z.number().nullable().optional(),
  ngan: z.number().nullable().optional(),
  squareWa: z.number().nullable().optional(),
  hasBoundaryMarker: z.boolean().nullable().optional(),
  boundaryMarkerRemark: z.string().nullable().optional(),
  isDocumentValidated: z.boolean().nullable().optional(),
  isMissingFromSurvey: z.boolean().nullable().optional(),
  governmentPricePerSqWa: z.number().nullable().optional(),
  governmentPrice: z.number().nullable().optional(),
  remark: z.string().nullable().optional(),
});

export const createLandFormBase = z.object({
  titles: z.array(landTitleItem).nullable().optional(),
});

export const createLandForm = buildFormSchema(allLandFields, createLandFormBase);

const surfaceFormItem = z.object({
  fromFloorNumber: z.coerce.number().nullable().optional(),
  toFloorNumber: z.coerce.number().nullable().optional(),
  floorType: z.string().nullable().optional(),
  floorStructureType: z.string().nullable().optional(),
  floorSurfaceType: z.string().nullable().optional(),
});

const depreciationPeriodFormItem = z.object({
  atYear: z.coerce.number().nullable().optional(),
  toYear: z.coerce.number().nullable().optional(),
  depreciationPerYear: z.coerce.number().nullable().optional(),
  totalDepreciationPct: z.coerce.number().nullable().optional(),
  priceDepreciation: z.coerce.number().nullable().optional(),
});

const depreciationFormItem = z.object({
  areaDescription: z.string().nullable().optional(),
  area: z.coerce.number().nullable().optional(),
  isBuilding: z.boolean().nullable().optional(),
  year: z.coerce.number().nullable().optional(),
  pricePerSqMBeforeDepreciation: z.coerce.number().nullable().optional(),
  priceBeforeDepreciation: z.coerce.number().nullable().optional(),
  depreciationMethod: z.string().nullable().optional(),
  depreciationYearPct: z.coerce.number().nullable().optional(),
  totalDepreciationPct: z.coerce.number().nullable().optional(),
  priceDepreciation: z.coerce.number().nullable().optional(),
  pricePerSqMAfterDepreciation: z.coerce.number().nullable().optional(),
  priceAfterDepreciation: z.coerce.number().nullable().optional(),
  depreciationPeriods: z.array(depreciationPeriodFormItem).nullable().optional(),
});

export const createBuildingFormBase = z.object({
  surfaces: z.array(surfaceFormItem).nullable().optional(),
  depreciationDetails: z.array(depreciationFormItem).nullable().optional(),
});

export const createBuildingForm = buildFormSchema(allBuildingFields, createBuildingFormBase);

const AreaDetailDto = z
  .object({
    id: z.string().uuid().nullable(),
    areaDescription: z.string().nullable(),
    areaSize: z.coerce.number().nullable(),
  })
  .passthrough();

export const createCondoFormBase = z.object({
  areaDetails: z.array(AreaDetailDto).nullable(),
});

export const createCondoForm = buildFormSchema(allCondoFields, createCondoFormBase);

export const createLandAndBuildingFormBase = z.object({
  titles: z.array(landTitleItem).nullable().optional(),
  surfaces: z.array(surfaceFormItem).nullable().optional(),
  depreciationDetails: z.array(depreciationFormItem).nullable().optional(),
});

export const createLandAndBuildingForm = buildFormSchema(
  allLandBuildingFields,
  createLandAndBuildingFormBase,
);

export const landAndBuildingPMAForm = z.object({
  buildingInsurancePrice: z.coerce.number().nullable(),
  sellingPrice: z.coerce.number().nullable(),
  forcedSalePrice: z.coerce.number().nullable(),
  titleNo: z.string().nullable().optional(),
  rawang: z.string().nullable().optional(),
  landNo: z.string().nullable().optional(),
  surveyNo: z.string().nullable().optional(),
  bookNumber: z.string().nullable().optional(),
  pageNumber: z.string().nullable().optional(),
  areaRai: z.number().int().nullable().optional(),
  areaNgan: z.number().int().nullable().optional(),
  areaSquareWa: z.number().nullable().optional(),
  subDistrict: z.string().min(1, 'Sub district is required.'),
  subDistrictName: z.string().nullable(),
  district: z.string().min(1, 'District is required.'),
  districtName: z.string().nullable(),
  province: z.string().min(1, 'Province is required.'),
  provinceName: z.string().nullable(),
});

export const condoPMAForm = z.object({
  buildingInsurancePrice: z.coerce.number().nullable(),
  sellingPrice: z.coerce.number().nullable(),
  forcedSalePrice: z.coerce.number().nullable(),
  builtOnTitleNumber: z.string().min(1, 'Built on title number is required.'),
  condoRegistrationNumber: z.string().min(1, 'Condo registration number is required.'),
  roomNumber: z.string().min(1, 'Room number is required.'),
  floorNumber: z.coerce.number(),
  buildingNumber: z.string().min(1, 'Building number is required.'),
  condoName: z.string().min(1, 'Condo name is required.'),
  subDistrict: z.string().min(1, 'Sub district is required.'),
  subDistrictName: z.string().nullable(),
  district: z.string().min(1, 'District is required.'),
  districtName: z.string().nullable(),
  province: z.string().min(1, 'Province is required.'),
  provinceName: z.string().nullable(),
});

export const factorDataDto = z
  .object({
    factorId: z.string().uuid().nullable().optional(),
    factorCode: z.string().nullable().optional(),
    value: z.any().nullable().optional(),
    otherRemarks: z.string().nullable().optional(),
    factorName: z.string().nullable().optional(),
    fieldName: z.string().nullable().optional(),
    dataType: z.string().nullable().optional(),
    fieldLength: z.coerce.number().nullable().optional(),
    fieldDecimal: z.coerce.number().nullable().optional(),
    parameterGroup: z.string().nullable().optional(),
    isActive: z.boolean().nullable().optional(),
    displaySeq: z.coerce.number().int().nullable().optional(),
  })
  .passthrough();

export const createMarketComparableForm = z
  .object({
    factorData: z.array(factorDataDto).nullable().optional(),
    notes: z.string().nullable().optional(),
    infoDateTime: z.string().datetime({ local: true, offset: true }).nullable().optional(),
    sourceInfo: z.string().nullable().optional(),
    surveyName: z.string(),
    templateId: z.string().uuid().nullable().optional(),
    templateCode: z.string().nullable().optional(),
    propertyType: z.string().nullable().optional(),
    comparableNumber: z.string().nullable().optional(),
    offerPrice: z.coerce.number().nullable().optional(),
    salePrice: z.coerce.number().nullable().optional(),
    saleDate: z.string().datetime({ local: true, offset: true }).nullable().optional(),
  })
  .passthrough();

export type createCondoFormType = z.infer<typeof createCondoForm>;
export type createBuildingFormType = z.infer<typeof createBuildingForm>;
export type createLandFormType = z.infer<typeof createLandForm>;
export type createLandAndBuildingFormType = z.infer<typeof createLandAndBuildingForm>;
export type landAndBuildingPMAFormType = z.infer<typeof landAndBuildingPMAForm>;
export type condoPMAFormType = z.infer<typeof condoPMAForm>;
export type createMarketComparableFormType = z.infer<typeof createMarketComparableForm>;

//===============================================================

export const createLandFormDefault: createLandFormType = {
  titles: [],
  propertyName: '',
  latitude: 0,
  longitude: 0,
  subDistrict: '',
  subDistrictName: '',
  district: '',
  districtName: '',
  province: '',
  provinceName: '',
  landOffice: '',
  landDescription: '',
  isOwnerVerified: false,
  ownerName: '',
  hasObligation: false,
  obligationDetails: '',
  isLandLocationVerified: false,
  landCheckMethodType: '',
  landCheckMethodTypeOther: '',
  street: '',
  soi: '',
  distanceFromMainRoad: 0,
  village: '',
  addressLocation: '',
  landShapeType: '',
  urbanPlanningType: '',
  landZoneType: [],
  plotLocationType: [],
  plotLocationTypeOther: '',
  landFillType: '',
  landFillTypeOther: '',
  landFillPercent: 0,
  soilLevel: 0,
  accessRoadWidth: 0,
  rightOfWay: 0,
  roadFrontage: 0,
  numberOfSidesFacingRoad: 0,
  roadPassInFrontOfLand: '',
  landAccessibilityType: '',
  landAccessibilityRemark: '',
  roadSurfaceType: '',
  roadSurfaceTypeOther: '',
  publicUtilityType: [],
  publicUtilityTypeOther: '',
  landUseType: [],
  landUseTypeOther: '',
  landEntranceExitType: [],
  landEntranceExitTypeOther: '',
  transportationAccessType: [],
  transportationAccessTypeOther: '',
  propertyAnticipationType: '',
  isExpropriated: false,
  expropriationRemark: '',
  isInExpropriationLine: false,
  expropriationLineRemark: '',
  royalDecree: '',
  isEncroached: false,
  encroachmentRemark: '',
  encroachmentArea: 0,
  hasElectricity: false,
  electricityDistance: 0,
  isLandlocked: false,
  landlockedRemark: '',
  isForestBoundary: false,
  forestBoundaryRemark: '',
  otherLegalLimitations: '',
  evictionType: [],
  evictionTypeOther: '',
  allocationType: '',
  northAdjacentArea: '',
  northBoundaryLength: 0,
  southAdjacentArea: '',
  southBoundaryLength: 0,
  eastAdjacentArea: '',
  eastBoundaryLength: 0,
  westAdjacentArea: '',
  westBoundaryLength: 0,
  pondArea: 0,
  pondDepth: 0,
  hasBuilding: false,
  hasBuildingOther: '',
  remark: '',
};

export const createBuildingFormDefault: createBuildingFormType = {
  ownerName: '',
  propertyName: '',
  buildingNumber: '',
  modelName: '',
  builtOnTitleNumber: '',
  isOwnerVerified: false,
  houseNumber: '',
  buildingConditionType: '',
  isUnderConstruction: false,
  constructionCompletionPercent: 100,
  constructionLicenseExpirationDate: null,
  isAppraisable: false,
  hasObligation: false,
  obligationDetails: '',
  buildingType: '',
  buildingTypeOther: '',
  numberOfFloors: 0,
  decorationType: '',
  decorationTypeOther: '',
  isEncroachingOthers: false,
  encroachingOthersRemark: '',
  encroachingOthersArea: 0,
  buildingMaterialType: '',
  buildingStyleType: '',
  isResidential: true,
  buildingAge: 0,
  residentialRemark: '',
  constructionStyleRemark: '',
  constructionStyleType: '',
  structureType: [],
  structureTypeOther: '',
  roofFrameType: [],
  roofFrameTypeOther: '',
  roofType: [],
  roofTypeOther: '',
  ceilingType: [],
  ceilingTypeOther: '',
  interiorWallType: [],
  interiorWallTypeOther: '',
  exteriorWallType: [],
  exteriorWallTypeOther: '',
  fenceType: [],
  fenceTypeOther: '',
  constructionType: '',
  constructionTypeOther: '',
  utilizationType: '',
  utilizationTypeOther: '',
  totalBuildingArea: 0,
  buildingInsurancePrice: 0,
  sellingPrice: 0,
  forcedSalePrice: 0,
  remark: '',
  surfaces: [],
  depreciationDetails: [],
};

export const createCondoFormDefault: createCondoFormType = {
  ownerName: '',
  propertyName: '',
  condoName: '',
  buildingNumber: '',
  modelName: '',
  builtOnTitleNumber: '',
  condoRegistrationNumber: '',
  roomNumber: '',
  floorNumber: 0,
  usableArea: 0,
  latitude: 0,
  longitude: 0,
  subDistrict: '',
  district: '',
  province: '',
  landOffice: '',
  isOwnerVerified: false,
  buildingConditionType: '',
  hasObligation: false,
  obligationDetails: '',
  isDocumentValidated: true,
  locationType: '',
  street: '',
  soi: '',
  distanceFromMainRoad: 0,
  accessRoadWidth: 0,
  rightOfWay: 0,
  roadSurfaceType: '',
  publicUtilityType: [],
  publicUtilityTypeOther: '',
  decorationType: '',
  decorationTypeOther: '',
  buildingAge: 0,
  numberOfFloors: 0,
  buildingFormType: '',
  constructionMaterialType: '',
  roomLayoutType: '',
  roomLayoutTypeOther: '',
  locationViewType: [],
  groundFloorMaterialType: '',
  groundFloorMaterialTypeOther: '',
  upperFloorMaterialType: '',
  upperFloorMaterialTypeOther: '',
  bathroomFloorMaterialType: '',
  bathroomFloorMaterialTypeOther: '',
  roofType: [],
  roofTypeOther: '',
  areaDetails: [],
  totalBuildingArea: 0,
  isExpropriated: false,
  expropriationRemark: '',
  isInExpropriationLine: false,
  expropriationLineRemark: '',
  royalDecree: '',
  isForestBoundary: false,
  forestBoundaryRemark: '',
  facilityType: [],
  facilityTypeOther: '',
  environmentType: [],
  buildingInsurancePrice: 0,
  sellingPrice: 0,
  forcedSalePrice: 0,
  remark: '',
};

export const createLandAndBuildingFormDefault: createLandAndBuildingFormType = {
  titles: [],
  propertyName: '',
  latitude: 0,
  longitude: 0,
  subDistrict: '',
  subDistrictName: '',
  district: '',
  districtName: '',
  province: '',
  provinceName: '',
  landOffice: '',
  landDescription: '',
  isOwnerVerified: true,
  ownerName: '',
  hasObligation: false,
  obligationDetails: '',
  isLandLocationVerified: false,
  landCheckMethodType: '',
  landCheckMethodTypeOther: '',
  street: '',
  soi: '',
  distanceFromMainRoad: 0,
  village: '',
  addressLocation: '',
  landShapeType: '',
  urbanPlanningType: '',
  landZoneType: [],
  plotLocationType: [],
  plotLocationTypeOther: '',
  landFillType: '',
  landFillTypeOther: '',
  landFillPercent: 0,
  soilLevel: 0,
  accessRoadWidth: 0,
  rightOfWay: 0,
  roadFrontage: 0,
  numberOfSidesFacingRoad: 0,
  roadPassInFrontOfLand: '',
  landAccessibilityType: '',
  landAccessibilityRemark: '',
  roadSurfaceType: '',
  roadSurfaceTypeOther: '',
  publicUtilityType: [],
  publicUtilityTypeOther: '',
  landUseType: [],
  landUseTypeOther: '',
  landEntranceExitType: [],
  landEntranceExitTypeOther: '',
  transportationAccessType: [],
  transportationAccessTypeOther: '',
  propertyAnticipationType: '',
  isExpropriated: false,
  expropriationRemark: '',
  isInExpropriationLine: false,
  expropriationLineRemark: '',
  royalDecree: '',
  isEncroached: false,
  encroachmentRemark: '',
  encroachmentArea: 0,
  hasElectricity: false,
  electricityDistance: 0,
  isLandlocked: false,
  landlockedRemark: '',
  isForestBoundary: false,
  forestBoundaryRemark: '',
  otherLegalLimitations: '',
  evictionType: [],
  evictionTypeOther: '',
  allocationType: '',
  northAdjacentArea: '',
  northBoundaryLength: 0,
  southAdjacentArea: '',
  southBoundaryLength: 0,
  eastAdjacentArea: '',
  eastBoundaryLength: 0,
  westAdjacentArea: '',
  westBoundaryLength: 0,
  pondArea: 0,
  pondDepth: 0,

  //Building
  buildingNumber: '',
  modelName: '',
  builtOnTitleNumber: '',
  houseNumber: '',
  buildingConditionType: '',
  isUnderConstruction: false,
  constructionCompletionPercent: 100,
  constructionLicenseExpirationDate: null,
  isAppraisable: false,
  buildingType: '',
  buildingTypeOther: '',
  numberOfFloors: 0,
  decorationType: '',
  decorationTypeOther: '',
  isEncroachingOthers: false,
  encroachingOthersRemark: '',
  encroachingOthersArea: 0,
  buildingMaterialType: '',
  buildingStyleType: '',
  isResidential: true,
  buildingAge: 0,
  residentialRemark: '',
  constructionStyleRemark: '',
  constructionStyleType: '',
  structureType: [],
  structureTypeOther: '',
  roofFrameType: [],
  roofFrameTypeOther: '',
  roofType: [],
  roofTypeOther: '',
  ceilingType: [],
  ceilingTypeOther: '',
  interiorWallType: [],
  interiorWallTypeOther: '',
  exteriorWallType: [],
  exteriorWallTypeOther: '',
  fenceType: [],
  fenceTypeOther: '',
  constructionType: '',
  constructionTypeOther: '',
  utilizationType: '',
  utilizationTypeOther: '',
  totalBuildingArea: 0,
  buildingInsurancePrice: 0,
  sellingPrice: 0,
  forcedSalePrice: 0,
  remark: '',
  surfaces: [],
  depreciationDetails: [],
};

export const landAndBuildingPMAFormDefault: landAndBuildingPMAFormType = {
  buildingInsurancePrice: 0,
  sellingPrice: 0,
  forcedSalePrice: 0,
  titleNo: '',
  rawang: '',
  landNo: '',
  surveyNo: '',
  bookNumber: '',
  pageNumber: '',
  areaRai: 0,
  areaNgan: 0,
  areaSquareWa: 0,
  subDistrict: '',
  subDistrictName: '',
  district: '',
  districtName: '',
  province: '',
  provinceName: '',
};

export const condoPMAFormDefault: condoPMAFormType = {
  buildingInsurancePrice: 0,
  sellingPrice: 0,
  forcedSalePrice: 0,
  builtOnTitleNumber: '',
  condoRegistrationNumber: '',
  roomNumber: '',
  floorNumber: 0,
  buildingNumber: '',
  condoName: '',
  subDistrict: '',
  subDistrictName: '',
  district: '',
  districtName: '',
  province: '',
  provinceName: '',
};

export const createMarketComparableFormDefault: createMarketComparableFormType = {
  factorData: [],
  surveyName: '',
  templateId: '',
  templateCode: '',
  notes: '',
  infoDateTime: '',
  sourceInfo: '',
  propertyType: '',
  comparableNumber: '',
  offerPrice: null,
  salePrice: null,
  saleDate: null,
};
