import { type CreateRequestRequestType } from './v1';

export const createRequestRequestDefaults: CreateRequestRequestType = {
  purpose: '',
  hasAppraisalBook: false,
  priority: 'Normal',
  reference: {
    prevAppraisalNo: '',
    prevAppraisalValue: '' as unknown as number,
    prevAppraisalDate: '2023-01-01T14:30:00Z',
  },
  channel: '',
  occurConstInspec: '' as unknown as number,
  loanDetail: {
    loanApplicationNo: '',
    limitAmt: '' as unknown as number,
    totalSellingPrice: '' as unknown as number,
  },
  address: {
    houseNo: '',
    roomNo: '',
    floorNo: '',
    locationIdentifier: '',
    moo: '',
    soi: '',
    road: '',
    subDistrict: '',
    district: '',
    province: '',
    postcode: '',
  },
  contact: {
    contactPersonName: '',
    contactPersonContactNo: '',
    projectCode: '',
  },
  fee: {
    feeType: '',
    feeRemark: '',
  },
  requestor: {
    requestorEmpId: '',
    requestorName: '',
    requestorEmail: '',
    requestorContactNo: '',
    requestorAo: '',
    requestorBranch: '',
    requestorBusinessUnit: '',
    requestorDepartment: '',
    requestorSection: '',
    requestorCostCenter: '',
  },
  customers: [],
  properties: [],
  comments: [],
  titles: [],
};

export const requestTitleDtoDefaults = {
  // Discriminator field - now at top level
  collateralType: '' as string,
  // Common fields - moved from collateral object
  titleNo: '',
  collateralStatus: '',
  owner: '',
  noOfBuilding: '' as unknown as number,
  titleDetail: '',
  titleDocuments: [],
  area: {
    rai: '' as unknown as number,
    ngan: '' as unknown as number,
    wa: '' as unknown as number,
    usageArea: '' as unknown as number,
  },
  condo: {
    condoName: '',
    condoBuildingNo: '',
    condoRoomNo: '',
    condoFloorNo: '',
  },
  titleAddress: {
    houseNo: '',
    roomNo: '',
    floorNo: '',
    buildingNo: '',
    moo: '',
    soi: '',
    road: '',
    subDistrict: '',
    district: '',
    province: '',
    postcode: '',
  },
  dopaAddress: {
    dopaHouseNo: '',
    dopaRoomNo: '',
    dopaFloorNo: '',
    dopaBuildingNo: '',
    dopaMoo: '',
    dopaSoi: '',
    dopaRoad: '',
    dopaSubDistrict: '',
    dopaDistrict: '',
    dopaProvince: '',
    dopaPostcode: '',
  },
  building: {
    buildingType: '',
  },
  vehicle: {
    vehicleType: '',
    vehicleRegistrationNo: '',
    vehAppointmentLocation: '',
  },
  machine: {
    machineStatus: '',
    machineType: '',
    machineRegistrationStatus: '',
    machineRegistrationNo: '',
    machineInvoiceNo: '',
    noOfMachine: '' as unknown as number,
  },
};
