import type { CreateBuildingRequestType } from './typeBuilding';
import { type CreateRequestRequestType, type RequestTitleDtoType } from './v1';
import type { CreateLandRequestType } from './v2';

export const createRequestRequestDefaults: CreateRequestRequestType = {
  purpose: '',
  hasAppraisalBook: false,
  priority: 'Normal',
  reference: {
    prevAppraisalNo: '',
    prevAppraisalValue: '' as unknown as number,
    prevAppraisalDate: '2023-01-01T14:30:00Z',
  },
  channel: '',
  occurConstInspec: '' as unknown as number,
  loanDetail: {
    loanApplicationNo: '',
    limitAmt: '' as unknown as number,
    totalSellingPrice: '' as unknown as number,
  },
  address: {
    houseNo: '',
    roomNo: '',
    floorNo: '',
    locationIdentifier: '',
    moo: '',
    soi: '',
    road: '',
    subDistrict: '',
    district: '',
    province: '',
    postcode: '',
  },
  contact: {
    contactPersonName: '',
    contactPersonContactNo: '',
    projectCode: '',
  },
  fee: {
    feeType: '',
    feeRemark: '',
  },
  requestor: {
    requestorEmpId: '',
    requestorName: '',
    requestorEmail: '',
    requestorContactNo: '',
    requestorAo: '',
    requestorBranch: '',
    requestorBusinessUnit: '',
    requestorDepartment: '',
    requestorSection: '',
    requestorCostCenter: '',
  },
  customers: [],
  properties: [],
  comments: [],
  titles: [],
};

export const requestTitleDtoDefaults: RequestTitleDtoType = {
  titleDocuments: [],
  collateral: {
    collateralType: 'land',
    collateralStatus: '',
    titleNo: '',
    owner: '',
    noOfBuilding: '' as unknown as number,
    titleDetail: '',
  },
  area: {
    rai: '' as unknown as number,
    ngan: '' as unknown as number,
    wa: '' as unknown as number,
    usageArea: '' as unknown as number,
  },
  condo: {
    collateralType: '',
    collateralStatus: '',
    titleNo: '',
    owner: '',
    noOfBuilding: '',
    titleDetail: '',
  },
  titleAddress: {
    houseNo: '',
    roomNo: '',
    floorNo: '',
    buildingNo: '',
    moo: '',
    soi: '',
    road: '',
    subDistrict: '',
    district: '',
    province: '',
    postcode: '',
  },
  dopaAddress: {
    houseNo: '',
    roomNo: '',
    floorNo: '',
    buildingNo: '',
    moo: '',
    soi: '',
    road: '',
    subDistrict: '',
    district: '',
    province: '',
    postcode: '',
  },
  building: {
    buildingType: '',
  },
  vehicle: {
    vehicleType: '',
    vehicleRegistrationNo: '',
    vehAppointmentLocation: '',
  },
  machine: {
    machineStatus: '',
    machineType: '',
    machineRegistrationStatus: '',
    machineRegistrationNo: '',
    machineInvoiceNo: '',
    noOfMachine: '' as unknown as number,
  },
};

export const createLandRequestDefaults: CreateLandRequestType = {
  landTitle: [],
  propertyName: '',
  latitude: '',
  longitude: '',
  subDistrict: '',
  district: '',
  province: '',
  landOffice: '',
  landDescription: '',
  landDetail: {
    verifiableOwner: false,
    owner: '',
    isObligation: '',
    obligation: '',
    landLocationVerification: false,
    landCheckMethod: '',
    landCheckOther: '',
    street: '',
    soi: '',
    distance: '',
    village: '',
    addressLocation: '',
    landShape: '',
    urbanPlanningType: '',
    location: [],
    plotLocation: [],
    plotLocationOther: '',
    landFill: [],
    landFillOther: '',
    landFillPct: 0,
    soilLevel: 0,
    roadWidth: '',
    rightOfWay: '',
    wideFrontageOfLand: 0,
    noOfSideFacingRoad: 0,
    roadPassInFrontOfLand: '',
    landAccessibility: '',
    landAccessibilityDesc: '',
    roadSurface: '',
    roadSurfaceOther: '',
    publicUtility: [],
    publicUtilityOther: '',
    landUse: [],
    landUseOther: '',
    landEntranceExit: [],
    landEntranceExitOther: '',
    transportation: [],
    transportationOther: '',
    anticipationOfProp: [],
    //
    isExpropriate: '',
    isExpropriateRemark: '',
    isLineExpropriate: '',
    inLineExpropriateRemark: '',
    royalDecree: '',
    isEncroached: '',
    isEncroachedRemark: '',
    encroachArea: 0,
    electricity: '',
    electricityDistance: 0,
    isLandlocked: '',
    isLandlockedRemark: '',
    isForestBoundary: '',
    isForestBoundaryRemark: '',
    limitationOther: '',
    //
    eviction: [],
    evictionOther: '',
    allocation: '',
    n_ConsecutiveArea: '',
    n_EstimateLength: 0,
    s_ConsecutiveArea: '',
    s_EstimateLength: 0,
    e_ConsecutiveArea: '',
    e_EstimateLength: 0,
    w_ConsecutiveArea: '',
    w_EstimateLength: 0,
    pondArea: 0,
    depthPit: 0,
    hasBuilding: '',
    hasBuildingOther: '',
    remark: '',
  },
};

export const createBuildingRequestDefault: CreateBuildingRequestType = {
  propertyName: '',
  buildingNumber: '',
  modelName: '',
  houseNumber: '',
  builtOnTitleNumber: '',
  buildingDetail: {
    verifiableOwner: false,
    owner: '',
    noHouseNumber: '',
    buildingCondition: '',
    underConst: 'NO',
    constCompletionPct: 100,
    licenseExpirationDate: '2023-01-01T14:30:00Z',
    isAppraise: true,
    isObligation: '1',
    obligation: '',
    buildingType: '',
    buidingTypeOther: '',
    totalFloor: 1,
    decoration: '',
    decorationOther: '',
    isEncroached: false,
    isEncroachedRemark: '',
    encroachArea: 0,
    buildingMaterial: '',
    buildingStyle: '',
    isResidential: true,
    buildingAge: 10,
    dueTo: '',
    constStyle: '',
    constStyleRemark: '',
    generalStructure: [],
    generalStructureOther: '',
    roofFrame: [],
    roofFrameOther: '',
    roof: [],
    roofOther: '',
    ceiling: [],
    ceilingOher: '',
    interiorWall: [],
    interiorWallOther: '',
    exteriorWall: [],
    exteriorWallOther: '',
    fence: [],
    fenceOther: '',
    constType: '',
    constTypeOther: '',
    utilization: '',
    useForOtherPurpose: '',
    buildingArea: 0,
    remark: '',
  },
};
