import { z } from 'zod';

const UserInfoDto = z.object({ userId: z.string(), username: z.string() });
const FeeDto = z.object({
  feePaymentType: z.string().nullable(),
  feeNotes: z.string().nullable(),
  absorbedAmount: z.number().nullable(),
});
const RequestDetailDto = z.object({
  hasAppraisalBook: z.boolean(),
  loanDetail: z.object({
    bankingSegment: z.string().nullable(),
    loanApplicationNumber: z.string().nullable(),
    facilityLimit: z.number().nullable(),
    additionalFacilityLimit: z.number().nullable(),
    previousFacilityLimit: z.number().nullable(),
    totalSellingPrice: z.number().nullable(),
  }),
  prevAppraisalId: z.string().uuid().nullable(),
  address: z.object({
    houseNumber: z.string().nullable(),
    projectName: z.string().nullable(),
    moo: z.string().nullable(),
    soi: z.string().nullable(),
    road: z.string().nullable(),
    subDistrict: z.string().nullable(),
    district: z.string().nullable(),
    province: z.string().nullable(),
    postcode: z.string().nullable(),
  }),
  contact: z.object({
    contactPersonName: z.string().nullable(),
    contactPersonPhone: z.string().nullable(),
    dealerCode: z.string().nullable(),
  }),
  appointment: z.object({
    appointmentDateTime: z.string().datetime({ offset: true }).nullable(),
    appointmentLocation: z.string().nullable(),
  }),
  fee: FeeDto.nullable(),
});
const RequestCustomerDto = z.object({
  name: z.string().nullable(),
  contactNumber: z.string().nullable(),
});
const RequestPropertyDto = z.object({
  propertyType: z.string().nullable(),
  buildingType: z.string().nullable(),
  sellingPrice: z.number().nullable(),
});
const AddressDto = z.object({
  houseNumber: z.string().nullable(),
  projectName: z.string().nullable(),
  moo: z.string().nullable(),
  soi: z.string().nullable(),
  road: z.string().nullable(),
  subDistrict: z.string().nullable(),
  district: z.string().nullable(),
  province: z.string().nullable(),
  postcode: z.string().nullable(),
});
const RequestTitleDocumentDto = z.object({
  id: z.string().uuid().nullable(),
  titleId: z.string().uuid().nullable(),
  documentId: z.string().uuid().nullable(),
  documentType: z.string().nullable(),
  filename: z.string().nullable(),
  prefix: z.string().nullable(),
  set: z.number().int(),
  documentDescription: z.string().nullable(),
  filePath: z.string().nullable(),
  createdWorkstation: z.string().nullable(),
  isRequired: z.boolean(),
  uploadedBy: z.string().nullable(),
  uploadedByName: z.string().nullable(),
  uploadedAt: z.string().datetime({ offset: true }),
});
const RequestTitleDto = z.object({
  id: z.string().uuid().nullable(),
  requestId: z.string().uuid(),
  collateralType: z.string(),
  collateralStatus: z.boolean(),
  titleNo: z.string().nullable(),
  deedType: z.string().nullable(),
  titleDetail: z.string().nullable(),
  rawang: z.string().nullable(),
  landNo: z.string().nullable(),
  surveyNo: z.string().nullable(),
  areaRai: z.number().int().nullable(),
  areaNgan: z.number().int().nullable(),
  areaSquareWa: z.number().nullable(),
  ownerName: z.string().nullable(),
  vehicleType: z.string().nullable(),
  vehicleAppointmentLocation: z.string().nullable(),
  vin: z.string().nullable(),
  licensePlateNumber: z.string().nullable(),
  vesselType: z.string().nullable(),
  vesselAppointmentLocation: z.string().nullable(),
  hullIdentificationNumber: z.string().nullable(),
  vesselRegistrationNumber: z.string().nullable(),
  registrationStatus: z.boolean(),
  registrationNo: z.string().nullable(),
  machineType: z.string().nullable(),
  installationStatus: z.string().nullable(),
  invoiceNumber: z.string().nullable(),
  numberOfMachine: z.number().int().nullable(),
  buildingType: z.string().nullable(),
  usableArea: z.number().nullable(),
  numberOfBuilding: z.number().int().nullable(),
  condoName: z.string().nullable(),
  buildingNo: z.string().nullable(),
  roomNo: z.string().nullable(),
  floorNo: z.string().nullable(),
  titleAddress: AddressDto,
  dopaAddress: AddressDto,
  notes: z.string().nullable(),
  documents: z.array(RequestTitleDocumentDto),
});
const RequestDocumentDto = z.object({
  id: z.string().uuid().nullable(),
  requestId: z.string().uuid(),
  documentId: z.string().uuid().nullable(),
  documentType: z.string(),
  fileName: z.string().nullable(),
  prefix: z.string().nullable(),
  set: z.number().int().nullable(),
  notes: z.string().nullable(),
  filePath: z.string().nullable(),
  source: z.string().nullable(),
  isRequired: z.boolean(),
  uploadedBy: z.string().nullable(),
  uploadedByName: z.string().nullable(),
  uploadedAt: z.string().datetime({ offset: true }).nullable(),
});
const RequestCommentDto = z.object({
  id: z.string().uuid(),
  requestId: z.string().uuid(),
  comment: z.string(),
  commentedBy: z.string(),
  commentedByName: z.string(),
  commentedAt: z.string().datetime({ offset: true }),
  lastModifiedAt: z.string().datetime({ offset: true }).nullable(),
});

export const createRequestFormSchema = z.object({
  purpose: z.string(),
  channel: z.string(),
  requestor: UserInfoDto,
  creator: UserInfoDto,
  priority: z.string(),
  isPma: z.boolean(),
  detail: RequestDetailDto,
  customers: z.array(RequestCustomerDto),
  properties: z.array(RequestPropertyDto),
  titles: z.array(RequestTitleDto),
  documents: z.array(RequestDocumentDto),
  comments: z.array(RequestCommentDto),
});
export type createRequestFormSchemaType = z.infer<typeof createRequestFormSchema>;
