import { z } from 'zod';

export const LandTitleDto = z
  .object({
    titleDeedNo: z.string(),
    bookNo: z.string(),
    pageNo: z.string(),
    landNo: z.string(),
    surveyNo: z.string(),
    sheetNo: z.string(),
    rai: z.coerce.number(),
    ngan: z.coerce.number(),
    wa: z.coerce.number(),
    totalSqWa: z.coerce.number(),
    documentType: z.string(),
    rawang: z.string(),
    aerialPhotoNo: z.string(),
    aerialPhotoName: z.string(),
    boundaryMarker: z.string().nullable(),
    boundartMakerOther: z.string().nullable(),
    docValidate: z.string(),
    isMissedOutSurvey: z.boolean(),
    pricePerSquareWa: z.coerce.number(),
    governmentPrice: z.coerce.number(),
  })
  .passthrough();

export const CreateLandRequest = z
  .object({
    landTitle: z.array(LandTitleDto),
    propertyName: z.string().nullable(),
    latitude: z.coerce.number(),
    longitude: z.coerce.number(),
    subDistrict: z.string().min(1, 'Sub district is required.'),
    district: z.string().min(1, 'District is required.'),
    province: z.string().min(1, 'Province is required.'),
    landOffice: z.string().min(1, 'Land office is required.'),
    landDescription: z.string().min(1, 'Land description is required.'),
    isOwnerVerified: z.boolean(),
    ownerName: z.string(),
    hasObligation: z.boolean(),
    obligationDetails: z.string(),
    isLandLocationVerified: z.boolean(),
    landCheckMethodType: z.string().nullable(),
    landCheckMethodTypeOther: z.string().nullable(),
    street: z.string().min(1, 'Street is required.'),
    soi: z.string().nullable(),
    distanceFromMainRoad: z.coerce.number().nullable(),
    village: z.string().nullable(),
    addressLocation: z.string().nullable(),
    landShapeType: z.string().nullable(),
    urbanPlanningType: z.string().nullable(),
    landZoneType: z.array(z.string()).nullable(),
    plotLocationType: z.array(z.string()).nullable(),
    plotLocationTypeOther: z.string().nullable(),
    landFillType: z.array(z.string()).nullable(),
    landFillTypeOther: z.string().nullable(),
    landFillPercent: z.coerce.number().nullable(),
    soilLevel: z.coerce.number().nullable(),
    accessRoadWidth: z.coerce.number().nullable(),
    rightOfWay: z.coerce.number().nullable(),
    roadFrontage: z.coerce.number().nullable(),
    numberOfSidesFacingRoad: z.coerce.number().nullable(),
    roadPassInFrontOfLand: z.string().nullable(),
    landAccessibilityType: z.string().nullable(),
    landAccessibilityRemark: z.string().nullable(),
    roadSurfaceType: z.string().nullable(),
    roadSurfaceTypeOther: z.string().nullable(),
    publicUtilityType: z.array(z.string()).nullable(),
    publicUtilityTypeOther: z.string().nullable(),
    landUseType: z.array(z.string()).nullable(),
    landUseTypeOther: z.string().nullable(),
    landEntranceExitType: z.array(z.string()).nullable(),
    landEntranceExitTypeOther: z.string().nullable(),
    transportationAccessType: z.array(z.string()).nullable(),
    transportationAccessTypeOther: z.string().nullable(),
    propertyAnticipationType: z.string().nullable(),
    isExpropriated: z.boolean(),
    expropriationRemark: z.string().nullable(),
    isInExpropriationLine: z.boolean().nullable(),
    expropriationLineRemark: z.string().nullable(),
    royalDecree: z.string().nullable(),
    isEncroached: z.boolean(),
    encroachmentRemark: z.string().nullable(),
    encroachmentArea: z.coerce.number().nullable(),
    hasElectricity: z.boolean(),
    electricityDistance: z.coerce.number().nullable(),
    isLandlocked: z.boolean(),
    landlockedRemark: z.string().nullable(),
    isForestBoundary: z.boolean(),
    forestBoundaryRemark: z.string().nullable(),
    otherLegalLimitations: z.string().nullable(),
    evictionType: z.array(z.string()).nullable(),
    evictionTypeOther: z.string().nullable(),
    allocationType: z.string().nullable(),
    northAdjacentArea: z.string().nullable(),
    northBoundaryLength: z.coerce.number().nullable(),
    southAdjacentArea: z.string().nullable(),
    southBoundaryLength: z.coerce.number().nullable(),
    eastAdjacentArea: z.string().nullable(),
    eastBoundaryLength: z.coerce.number().nullable(),
    westAdjacentArea: z.string().nullable(),
    westBoundaryLength: z.coerce.number().nullable(),
    pondArea: z.coerce.number().nullable(),
    pondDepth: z.coerce.number().nullable(),
    hasBuilding: z.boolean(),
    hasBuildingOther: z.string().nullable(),
    remark: z.string().nullable(),
  })
  .partial()
  .passthrough();

const GetLandPropertyByIdResult = z
  .object({
    landTitle: z.array(LandTitleDto),
    propertyName: z.string().nullable(),
    latitude: z.coerce.number(),
    longitude: z.coerce.number(),
    subDistrict: z.string().min(1, 'Sub district is required.'),
    district: z.string().min(1, 'District is required.'),
    province: z.string().min(1, 'Province is required.'),
    landOffice: z.string().min(1, 'Land office is required.'),
    landDescription: z.string().min(1, 'Land description is required.'),
    isOwnerVerified: z.boolean(),
    ownerName: z.string(),
    hasObligation: z.boolean(),
    obligationDetails: z.string(),
    isLandLocationVerified: z.boolean(),
    landCheckMethodType: z.string().nullable(),
    landCheckMethodTypeOther: z.string().nullable(),
    street: z.string().min(1, 'Street is required.'),
    soi: z.string().nullable(),
    distanceFromMainRoad: z.coerce.number().nullable(),
    village: z.string().nullable(),
    addressLocation: z.string().nullable(),
    landShapeType: z.string().nullable(),
    urbanPlanningType: z.string().nullable(),
    landZoneType: z.array(z.string()).nullable(),
    plotLocationType: z.array(z.string()).nullable(),
    plotLocationTypeOther: z.string().nullable(),
    landFillType: z.array(z.string()).nullable(),
    landFillTypeOther: z.string().nullable(),
    landFillPercent: z.coerce.number().nullable(),
    soilLevel: z.coerce.number().nullable(),
    accessRoadWidth: z.coerce.number().nullable(),
    rightOfWay: z.coerce.number().nullable(),
    roadFrontage: z.coerce.number().nullable(),
    numberOfSidesFacingRoad: z.coerce.number().nullable(),
    roadPassInFrontOfLand: z.string().nullable(),
    landAccessibilityType: z.string().nullable(),
    landAccessibilityRemark: z.string().nullable(),
    roadSurfaceType: z.string().nullable(),
    roadSurfaceTypeOther: z.string().nullable(),
    publicUtilityType: z.array(z.string()).nullable(),
    publicUtilityTypeOther: z.string().nullable(),
    landUseType: z.array(z.string()).nullable(),
    landUseTypeOther: z.string().nullable(),
    landEntranceExitType: z.array(z.string()).nullable(),
    landEntranceExitTypeOther: z.string().nullable(),
    transportationAccessType: z.array(z.string()).nullable(),
    transportationAccessTypeOther: z.string().nullable(),
    propertyAnticipationType: z.string().nullable(),
    isExpropriated: z.boolean(),
    expropriationRemark: z.string().nullable(),
    isInExpropriationLine: z.boolean().nullable(),
    expropriationLineRemark: z.string().nullable(),
    royalDecree: z.string().nullable(),
    isEncroached: z.boolean(),
    encroachmentRemark: z.string().nullable(),
    encroachmentArea: z.coerce.number().nullable(),
    hasElectricity: z.boolean(),
    electricityDistance: z.coerce.number().nullable(),
    isLandlocked: z.boolean(),
    landlockedRemark: z.string().nullable(),
    isForestBoundary: z.boolean(),
    forestBoundaryRemark: z.string().nullable(),
    otherLegalLimitations: z.string().nullable(),
    evictionType: z.array(z.string()).nullable(),
    evictionTypeOther: z.string().nullable(),
    allocationType: z.string().nullable(),
    northAdjacentArea: z.string().nullable(),
    northBoundaryLength: z.coerce.number().nullable(),
    southAdjacentArea: z.string().nullable(),
    southBoundaryLength: z.coerce.number().nullable(),
    eastAdjacentArea: z.string().nullable(),
    eastBoundaryLength: z.coerce.number().nullable(),
    westAdjacentArea: z.string().nullable(),
    westBoundaryLength: z.coerce.number().nullable(),
    pondArea: z.coerce.number().nullable(),
    pondDepth: z.coerce.number().nullable(),
    hasBuilding: z.boolean(),
    hasBuildingOther: z.string().nullable(),
    remark: z.string().nullable(),
  })
  .passthrough();

export const CreateLandResponse = z.object({ id: z.coerce.number().int() }).passthrough();

const UpdateLandRequest = z.object({
  landTitle: z.array(LandTitleDto),
  propertyName: z.string().nullable(),
  latitude: z.coerce.number(),
  longitude: z.coerce.number(),
  subDistrict: z.string().min(1, 'Sub district is required.'),
  district: z.string().min(1, 'District is required.'),
  province: z.string().min(1, 'Province is required.'),
  landOffice: z.string().min(1, 'Land office is required.'),
  landDescription: z.string().min(1, 'Land description is required.'),
  isOwnerVerified: z.boolean(),
  ownerName: z.string(),
  hasObligation: z.boolean(),
  obligationDetails: z.string(),
  isLandLocationVerified: z.boolean(),
  landCheckMethodType: z.string().nullable(),
  landCheckMethodTypeOther: z.string().nullable(),
  street: z.string().min(1, 'Street is required.'),
  soi: z.string().nullable(),
  distanceFromMainRoad: z.coerce.number().nullable(),
  village: z.string().nullable(),
  addressLocation: z.string().nullable(),
  landShapeType: z.string().nullable(),
  urbanPlanningType: z.string().nullable(),
  landZoneType: z.array(z.string()).nullable(),
  plotLocationType: z.array(z.string()).nullable(),
  plotLocationTypeOther: z.string().nullable(),
  landFillType: z.array(z.string()).nullable(),
  landFillTypeOther: z.string().nullable(),
  landFillPercent: z.coerce.number().nullable(),
  soilLevel: z.coerce.number().nullable(),
  accessRoadWidth: z.coerce.number().nullable(),
  rightOfWay: z.coerce.number().nullable(),
  roadFrontage: z.coerce.number().nullable(),
  numberOfSidesFacingRoad: z.coerce.number().nullable(),
  roadPassInFrontOfLand: z.string().nullable(),
  landAccessibilityType: z.string().nullable(),
  landAccessibilityRemark: z.string().nullable(),
  roadSurfaceType: z.string().nullable(),
  roadSurfaceTypeOther: z.string().nullable(),
  publicUtilityType: z.array(z.string()).nullable(),
  publicUtilityTypeOther: z.string().nullable(),
  landUseType: z.array(z.string()).nullable(),
  landUseTypeOther: z.string().nullable(),
  landEntranceExitType: z.array(z.string()).nullable(),
  landEntranceExitTypeOther: z.string().nullable(),
  transportationAccessType: z.array(z.string()).nullable(),
  transportationAccessTypeOther: z.string().nullable(),
  propertyAnticipationType: z.string().nullable(),
  isExpropriated: z.boolean(),
  expropriationRemark: z.string().nullable(),
  isInExpropriationLine: z.boolean().nullable(),
  expropriationLineRemark: z.string().nullable(),
  royalDecree: z.string().nullable(),
  isEncroached: z.boolean(),
  encroachmentRemark: z.string().nullable(),
  encroachmentArea: z.coerce.number().nullable(),
  hasElectricity: z.boolean(),
  electricityDistance: z.coerce.number().nullable(),
  isLandlocked: z.boolean(),
  landlockedRemark: z.string().nullable(),
  isForestBoundary: z.boolean(),
  forestBoundaryRemark: z.string().nullable(),
  otherLegalLimitations: z.string().nullable(),
  evictionType: z.array(z.string()).nullable(),
  evictionTypeOther: z.string().nullable(),
  allocationType: z.string().nullable(),
  northAdjacentArea: z.string().nullable(),
  northBoundaryLength: z.coerce.number().nullable(),
  southAdjacentArea: z.string().nullable(),
  southBoundaryLength: z.coerce.number().nullable(),
  eastAdjacentArea: z.string().nullable(),
  eastBoundaryLength: z.coerce.number().nullable(),
  westAdjacentArea: z.string().nullable(),
  westBoundaryLength: z.coerce.number().nullable(),
  pondArea: z.coerce.number().nullable(),
  pondDepth: z.coerce.number().nullable(),
  hasBuilding: z.boolean(),
  hasBuildingOther: z.string().nullable(),
  remark: z.string().nullable(),
});

const UpdateLandResponse = z.object({ isSuccess: z.boolean() }).passthrough();
const DeletePropertyResponse = z.object({ isSuccess: z.boolean() }).passthrough();

export const schemas = {
  GetLandPropertyByIdResult,
  UpdateLandRequest,
  UpdateLandResponse,
};

export type CreateLandRequestType = z.infer<typeof CreateLandRequest>;
export type CreateLandResponseType = z.infer<typeof CreateLandResponse>;
export type LandTitleDtoType = z.infer<typeof LandTitleDto>;
export type DeletePropertyResponseType = z.infer<typeof DeletePropertyResponse>;
