import { z } from 'zod';

export const LandTitleDto = z
  .object({
    titleDeedNo: z.string(),
    bookNo: z.string(),
    pageNo: z.string(),
    landNo: z.string(),
    surveyNo: z.string(),
    sheetNo: z.string(),
    rai: z.coerce.number(),
    ngan: z.coerce.number(),
    wa: z.coerce.number(),
    totalSqWa: z.coerce.number(),
    documentType: z.string(),
    rawang: z.string(),
    aerialPhotoNo: z.string(),
    aerialPhotoName: z.string(),
    boundaryMarker: z.string().nullable(),
    boundartMakerOther: z.string().nullable(),
    docValidate: z.string(),
    isMissedOutSurvey: z.boolean(),
    pricePerSquareWa: z.coerce.number(),
    governmentPrice: z.coerce.number(),
  })
  .passthrough();

export const CreateLandRequest = z
  .object({
    landTitle: z.array(LandTitleDto),
    propertyName: z.string(),
    latitude: z.coerce.number(),
    longitude: z.coerce.number(),
    subDistrict: z.string(),
    district: z.string(),
    province: z.string(),
    landOffice: z.string(),
    landDescription: z.string(),
    isOwnerVerified: z.boolean(),
    ownerName: z.string(),
    hasObligation: z.boolean(),
    obligationDetails: z.string(),
    isLandLocationVerified: z.boolean(),
    landCheckMethodType: z.string(),
    landCheckMethodTypeOther: z.string(),
    street: z.string(),
    soi: z.string(),
    distanceFromMainRoad: z.coerce.number(),
    village: z.string(),
    addressLocation: z.string(),
    landShapeType: z.string(),
    urbanPlanningType: z.string(),
    landZoneType: z.array(z.string()),
    plotLocationType: z.array(z.string()),
    plotLocationTypeOther: z.string(),
    landFillStatusType: z.array(z.string()),
    landFillStatusTypeOther: z.string(),
    landFillPercent: z.coerce.number(),
    soilLevel: z.coerce.number(),
    accessRoadWidth: z.coerce.number(),
    rightOfWay: z.coerce.number(),
    roadFrontage: z.coerce.number(),
    numberOfSidesFacingRoad: z.coerce.number(),
    roadPassInFrontOfLand: z.string(),
    landAccessibility: z.string(),
    landAccessibilityDesc: z.string(),
    roadSurface: z.string(),
    roadSurfaceOther: z.string(),
    publicUtility: z.array(z.string()),
    publicUtilityOther: z.string(),
    landUse: z.array(z.string()),
    landUseOther: z.string(),
    landEntranceExit: z.array(z.string()),
    landEntranceExitOther: z.string(),
    transportation: z.array(z.string()),
    transportationOther: z.string(),
    anticipationOfProp: z.array(z.string()),
    isExpropriate: z.string(),
    isExpropriateRemark: z.string(),
    isLineExpropriate: z.string(),
    inLineExpropriateRemark: z.string(),
    royalDecree: z.string(),
    isEncroached: z.boolean(),
    encroachedRemark: z.string(),
    encroachArea: z.coerce.number(),
    hasElectricity: z.boolean(),
    electricityDistance: z.coerce.number(),
    isLandlocked: z.boolean(),
    landlockedRemark: z.string(),
    isForestBoundary: z.boolean(),
    forestBoundaryRemark: z.string(),
    otherLegalLimitations: z.string(),
    evictionStatusType: z.array(z.string()),
    evictionStatusTypeOther: z.string(),
    allocationStatusType: z.string(),
    northAdjacentArea: z.string(),
    northBoundaryLength: z.coerce.number(),
    southAdjacentArea: z.string(),
    southBoundaryLength: z.coerce.number(),
    eastAdjacentArea: z.string(),
    eastBoundaryLength: z.coerce.number(),
    westAdjacentArea: z.string(),
    westBoundaryLength: z.coerce.number(),
    pondArea: z.coerce.number(),
    pondDepth: z.coerce.number(),
    hasBuilding: z.boolean(),
    hasBuildingOther: z.string(),
    remark: z.string(),
  })
  .partial()
  .passthrough();

export const CreateLandResponse = z.object({ id: z.coerce.number().int() }).passthrough();

export type CreateLandRequestType = z.infer<typeof CreateLandRequest>;
export type CreateLandResponseType = z.infer<typeof CreateLandResponse>;
export type LandTitleDtoType = z.infer<typeof LandTitleDto>;
