import type { createLandFormType } from '@/features/appraisal/schemas/form';
import type { GetLandPropertyByIdResultType } from '@/features/appraisal/api';

export const mapLandPropertyResponseToForm = (
  response: GetLandPropertyByIdResultType,
): createLandFormType => {
  return {
    propertyName: response.propertyName ?? '',
    latitude: response.latitude ?? 0,
    longitude: response.longitude ?? 0,
    subDistrict: response.subDistrict ?? '',
    subDistrictName: '',
    district: response.district ?? '',
    districtName: '',
    province: response.province ?? '',
    provinceName: '',
    landOffice: response.landOffice ?? '',
    landDescription: response.landDescription ?? '',
    isOwnerVerified: response.isOwnerVerified ?? false,
    ownerName: response.ownerName ?? '',
    hasObligation: response.hasObligation ?? false,
    obligationDetails: response.obligationDetails ?? '',
    isLandLocationVerified: response.isLandLocationVerified ?? false,
    landCheckMethodType: response.landCheckMethodType ?? '',
    landCheckMethodTypeOther: response.landCheckMethodTypeOther ?? '',
    street: response.street ?? '',
    soi: response.soi ?? '',
    distanceFromMainRoad: response.distanceFromMainRoad ?? 0,
    village: response.village ?? '',
    addressLocation: response.addressLocation ?? '',
    landShapeType: response.landShapeType ?? '',
    urbanPlanningType: response.urbanPlanningType ?? '',
    landZoneType: response.landZoneType ?? [],
    plotLocationType: response.plotLocationType ?? [],
    plotLocationTypeOther: response.plotLocationTypeOther ?? '',
    landFillStatusType: response.landFillStatusType ?? [],
    landFillStatusTypeOther: response.landFillStatusTypeOther ?? '',
    landFillPercent: response.landFillPercent ?? 0,
    soilLevel: response.soilLevel ?? 0,
    accessRoadWidth: response.accessRoadWidth ?? 0,
    rightOfWay: response.rightOfWay ?? 0,
    roadFrontage: response.roadFrontage ?? 0,
    numberOfSidesFacingRoad: response.numberOfSidesFacingRoad ?? 0,
    roadPassInFrontOfLand: response.roadPassInFrontOfLand ?? '',
    landAccessibilityType: response.landAccessibilityType ?? '',
    landAccessibilityRemark: response.landAccessibilityRemark ?? '',
    roadSurfaceType: response.roadSurfaceType ?? '',
    roadSurfaceTypeOther: response.roadSurfaceTypeOther ?? '',
    publicUtilityType: response.publicUtilityType ?? [],
    publicUtilityTypeOther: response.publicUtilityTypeOther ?? '',
    landUseType: response.landUseType ?? [],
    landUseTypeOther: response.landUseTypeOther ?? '',
    landEntranceExitType: response.landEntranceExitType ?? [],
    landEntranceExitTypeOther: response.landEntranceExitTypeOther ?? '',
    transportationAccessType: response.transportationAccessType ?? [],
    transportationAccessTypeOther: response.transportationAccessTypeOther ?? '',
    propertyAnticipationType: response.propertyAnticipationType ?? '',
    isExpropriated: response.isExpropriated ?? false,
    expropriationRemark: response.expropriationRemark ?? '',
    isInExpropriationLine: response.isInExpropriationLine ?? false,
    expropriationLineRemark: response.expropriationLineRemark ?? '',
    royalDecree: response.royalDecree ?? '',
    isEncroached: response.isEncroached ?? false,
    encroachedRemark: response.encroachedRemark ?? '',
    encroachArea: response.encroachArea ?? 0,
    hasElectricity: response.hasElectricity ?? false,
    electricityDistance: response.electricityDistance ?? 0,
    isLandlocked: response.isLandlocked ?? false,
    landlockedRemark: response.landlockedRemark ?? '',
    isForestBoundary: response.isForestBoundary ?? false,
    forestBoundaryRemark: response.forestBoundaryRemark ?? '',
    otherLegalLimitations: response.otherLegalLimitations ?? '',
    evictionStatusType: response.evictionStatusType ?? [],
    evictionStatusTypeOther: response.evictionStatusTypeOther ?? '',
    allocationStatusType: response.allocationStatusType ?? '',
    northAdjacentArea: response.northAdjacentArea ?? '',
    northBoundaryLength: response.northBoundaryLength ?? 0,
    southAdjacentArea: response.southAdjacentArea ?? '',
    southBoundaryLength: response.southBoundaryLength ?? 0,
    eastAdjacentArea: response.eastAdjacentArea ?? '',
    eastBoundaryLength: response.eastBoundaryLength ?? 0,
    westAdjacentArea: response.westAdjacentArea ?? '',
    westBoundaryLength: response.westBoundaryLength ?? 0,
    pondArea: response.pondArea ?? 0,
    pondDepth: response.pondDepth ?? 0,
    hasBuilding: response.hasBuilding ?? false,
    hasBuildingOther: response.hasBuildingOther ?? '',
    remark: response.remark ?? '',
  };
};
