import type {
  createBuildingFormType,
  createCondoFormType,
  createLandFormType,
} from '@/features/appraisal/schemas/form';
import type { GetLandPropertyByIdResultType } from '@/features/appraisal/api';
import type { GetBuildingPropertyByIdResultType } from '@/shared/forms/typeBuilding';
import type { GetCondoPropertyByIdResultType } from '@/shared/forms/typeCondo';

export const mapLandPropertyResponseToForm = (
  response: GetLandPropertyByIdResultType,
): createLandFormType => {
  return {
    propertyName: response.propertyName ?? '',
    latitude: response.latitude ?? 0,
    longitude: response.longitude ?? 0,
    subDistrict: response.subDistrict ?? '',
    subDistrictName: '',
    district: response.district ?? '',
    districtName: '',
    province: response.province ?? '',
    provinceName: '',
    landOffice: response.landOffice ?? '',
    landDescription: response.landDescription ?? '',
    isOwnerVerified: response.isOwnerVerified ?? false,
    ownerName: response.ownerName ?? '',
    hasObligation: response.hasObligation ?? false,
    obligationDetails: response.obligationDetails ?? '',
    isLandLocationVerified: response.isLandLocationVerified ?? false,
    landCheckMethodType: response.landCheckMethodType ?? '',
    landCheckMethodTypeOther: response.landCheckMethodTypeOther ?? '',
    street: response.street ?? '',
    soi: response.soi ?? '',
    distanceFromMainRoad: response.distanceFromMainRoad ?? 0,
    village: response.village ?? '',
    addressLocation: response.addressLocation ?? '',
    landShapeType: response.landShapeType ?? '',
    urbanPlanningType: response.urbanPlanningType ?? '',
    landZoneType: response.landZoneType ?? [],
    plotLocationType: response.plotLocationType ?? [],
    plotLocationTypeOther: response.plotLocationTypeOther ?? '',
    landFillStatusType: response.landFillStatusType ?? [],
    landFillStatusTypeOther: response.landFillStatusTypeOther ?? '',
    landFillPercent: response.landFillPercent ?? 0,
    soilLevel: response.soilLevel ?? 0,
    accessRoadWidth: response.accessRoadWidth ?? 0,
    rightOfWay: response.rightOfWay ?? 0,
    roadFrontage: response.roadFrontage ?? 0,
    numberOfSidesFacingRoad: response.numberOfSidesFacingRoad ?? 0,
    roadPassInFrontOfLand: response.roadPassInFrontOfLand ?? '',
    landAccessibilityType: response.landAccessibilityType ?? '',
    landAccessibilityRemark: response.landAccessibilityRemark ?? '',
    roadSurfaceType: response.roadSurfaceType ?? '',
    roadSurfaceTypeOther: response.roadSurfaceTypeOther ?? '',
    publicUtilityType: response.publicUtilityType ?? [],
    publicUtilityTypeOther: response.publicUtilityTypeOther ?? '',
    landUseType: response.landUseType ?? [],
    landUseTypeOther: response.landUseTypeOther ?? '',
    landEntranceExitType: response.landEntranceExitType ?? [],
    landEntranceExitTypeOther: response.landEntranceExitTypeOther ?? '',
    transportationAccessType: response.transportationAccessType ?? [],
    transportationAccessTypeOther: response.transportationAccessTypeOther ?? '',
    propertyAnticipationType: response.propertyAnticipationType ?? '',
    isExpropriated: response.isExpropriated ?? false,
    expropriationRemark: response.expropriationRemark ?? '',
    isInExpropriationLine: response.isInExpropriationLine ?? false,
    expropriationLineRemark: response.expropriationLineRemark ?? '',
    royalDecree: response.royalDecree ?? '',
    isEncroached: response.isEncroached ?? false,
    encroachedRemark: response.encroachedRemark ?? '',
    encroachArea: response.encroachArea ?? 0,
    hasElectricity: response.hasElectricity ?? false,
    electricityDistance: response.electricityDistance ?? 0,
    isLandlocked: response.isLandlocked ?? false,
    landlockedRemark: response.landlockedRemark ?? '',
    isForestBoundary: response.isForestBoundary ?? false,
    forestBoundaryRemark: response.forestBoundaryRemark ?? '',
    otherLegalLimitations: response.otherLegalLimitations ?? '',
    evictionStatusType: response.evictionStatusType ?? [],
    evictionStatusTypeOther: response.evictionStatusTypeOther ?? '',
    allocationStatusType: response.allocationStatusType ?? '',
    northAdjacentArea: response.northAdjacentArea ?? '',
    northBoundaryLength: response.northBoundaryLength ?? 0,
    southAdjacentArea: response.southAdjacentArea ?? '',
    southBoundaryLength: response.southBoundaryLength ?? 0,
    eastAdjacentArea: response.eastAdjacentArea ?? '',
    eastBoundaryLength: response.eastBoundaryLength ?? 0,
    westAdjacentArea: response.westAdjacentArea ?? '',
    westBoundaryLength: response.westBoundaryLength ?? 0,
    pondArea: response.pondArea ?? 0,
    pondDepth: response.pondDepth ?? 0,
    hasBuilding: response.hasBuilding ?? false,
    hasBuildingOther: response.hasBuildingOther ?? '',
    remark: response.remark ?? '',
  };
};

export const mapBuildingPropertyResponseToForm = (
  response: GetBuildingPropertyByIdResultType,
): createBuildingFormType => {
  return {
    ownerName: response.ownerName ?? '',
    propertyName: response.propertyName ?? '',
    buildingNumber: response.buildingNumber ?? '',
    modelName: response.modelName ?? '',
    builtOnTitleNumber: response.builtOnTitleNumber ?? '',
    isOwnerVerified: response.isOwnerVerified ?? false,
    houseNumber: response.houseNumber ?? '',
    buildingCondition: response.buildingCondition ?? '',
    isUnderConstruction: response.isUnderConstruction ?? false,
    constructionCompletionPercent: response.constructionCompletionPercent ?? 100,
    constructionLicenseExpirationDate: response.constructionLicenseExpirationDate ?? '',
    isAppraisable: response.isAppraisable ?? false,
    hasObligation: response.hasObligation ?? false,
    obligationDetails: response.obligationDetails ?? '',
    buildingType: response.buildingType ?? '',
    buildingTypeOther: response.buildingTypeOther ?? '',
    numberOfFloors: response.numberOfFloors ?? 0,
    decorationType: response.decorationType ?? '',
    decorationtypeOther: response.decorationtypeOther ?? '',
    isEncroached: response.isEncroached ?? false,
    encroachmentRemark: response.encroachmentRemark ?? '',
    encroachmentArea: response.encroachmentArea ?? 0,
    buildingMaterial: response.buildingMaterial ?? '',
    buildingStyle: response.buildingStyle ?? '',
    isResidential: response.isResidential ?? false,
    buildingAge: response.buildingAge ?? 0,
    isResidentialRemark: response.isResidentialRemark ?? '',
    constructionStyleRemark: response.constructionStyleRemark ?? '',
    constructionStyleType: response.constructionStyleType ?? '',
    structureType: response.structureType ?? [],
    structureTypeOther: response.structureTypeOther ?? '',
    roofFrameType: response.roofFrameType ?? [],
    roofFrameTypeOther: response.roofFrameTypeOther ?? '',
    roofType: response.roofType ?? [],
    roofTypeOther: response.roofTypeOther ?? '',
    ceilingType: response.ceilingType ?? [],
    ceilingTypeOther: response.ceilingTypeOther ?? '',
    interiorWallType: response.interiorWallType ?? [],
    interiorWallTypeOther: response.interiorWallTypeOther ?? '',
    exteriorWallType: response.exteriorWallType ?? [],
    exteriorWallTypeOther: response.exteriorWallTypeOther ?? '',
    fenceType: response.fenceType ?? [],
    fenceTypeOther: response.fenceTypeOther ?? '',
    constructionType: response.constructionType ?? '',
    constructionTypeOther: response.constructionTypeOther ?? '',
    utilizationType: response.utilizationType ?? '',
    otherPurposeUsage: response.otherPurposeUsage ?? '',
    totalBuildingArea: response.totalBuildingArea ?? 0,
    buildingInsurancePrice: response.buildingInsurancePrice ?? 0,
    sellingPrice: response.sellingPrice ?? 0,
    forcedSalePrice: response.forcedSalePrice ?? 0,
    remark: response.remark ?? '',
  };
};

export const mapCondoPropertyResponseToForm = (
  response: GetCondoPropertyByIdResultType,
): createCondoFormType => {
  return {
    ownerName: response.ownerName ?? '',
    propertyName: response.propertyName ?? '',
    condoName: response.condoName ?? '',
    buildingNumber: response.buildingNumber ?? '',
    modelName: response.modelName ?? '',
    builtOnTitleNo: response.builtOnTitleNo ?? '',
    condoRegisNo: response.condoRegisNo ?? '',
    roomNo: response.roomNo ?? '',
    floorNo: response.floorNo ?? 0,
    usableArea: response.usableArea ?? 0,
    latitude: response.latitude ?? 0,
    longitude: response.longitude ?? 0,
    subDistrict: response.subDistrict ?? '',
    district: response.district ?? '',
    province: response.province ?? '',
    landOffice: response.landOffice ?? '',
    isOwnerVerified: response.isOwnerVerified ?? false,
    buildingCondition: response.buildingCondition ?? '',
    hasObligation: response.hasObligation ?? false,
    obligationDetails: response.obligationDetails ?? '',
    docValidate: response.docValidate ?? true,
    locationType: response.locationType ?? '',
    street: response.street ?? '',
    soi: response.soi ?? '',
    distanceFromMainRoad: response.distanceFromMainRoad ?? 0,
    accessRoadWidth: response.accessRoadWidth ?? 0,
    rightOfWay: response.rightOfWay ?? '',
    roadSurfaceType: response.roadSurfaceType ?? '',
    publicUtility: response.publicUtility ?? [],
    publicUtilityOther: response.publicUtilityOther ?? '',
    decoration: response.decoration ?? '',
    decorationOther: response.decorationOther ?? '',
    buildingAge: response.buildingAge ?? 0,
    numberOfFloor: response.numberOfFloor ?? 0,
    buildingForm: response.buildingForm ?? '',
    constructionMaterialType: response.constructionMaterialType ?? '',
    roomLayoutType: response.roomLayoutType ?? '',
    roomLayoutTypeOther: response.roomLayoutTypeOther ?? '',
    locationView: response.locationView ?? [],
    groundFloorMaterial: response.groundFloorMaterial ?? '',
    groundFloorMaterialOther: response.groundFloorMaterialOther ?? '',
    upperFloorMaterial: response.upperFloorMaterial ?? '',
    upperFloorMaterialOther: response.upperFloorMaterialOther ?? '',
    bathroomFloorMaterial: response.bathroomFloorMaterial ?? '',
    bathroomFloorMaterialOther: response.bathroomFloorMaterialOther ?? '',
    roofType: response.roofType ?? '',
    roofTypeOther: response.roofTypeOther ?? '',
    totalBuildingArea: response.totalBuildingArea ?? 0,
    isExpropriated: response.isExpropriated ?? false,
    expropriationRemark: response.expropriationRemark ?? '',
    isInExpropriationLine: response.isInExpropriationLine ?? false,
    expropriationLineRemark: response.expropriationLineRemark ?? '',
    royalDecree: response.royalDecree ?? '',
    isForestBoundary: response.isForestBoundary ?? false,
    forestBoundaryRemark: response.forestBoundaryRemark ?? '',
    facilityType: response.facilityType ?? [],
    facilityTypeOther: response.facilityTypeOther ?? '',
    environmentType: response.environmentType ?? [],
    buildingInsurancePrice: response.buildingInsurancePrice ?? 0,
    sellingPrice: response.sellingPrice ?? 0,
    forcedSalePrice: response.forcedSalePrice ?? 0,
    remark: response.remark ?? '',
  };
};
