import type {
  condoPMAFormType,
  createBuildingFormType,
  createCondoFormType,
  createLandAndBuildingFormType,
  createLandFormType,
  landAndBuildingPMAFormType,
  summaryDecisionFormType,
} from '@/features/appraisal/schemas/form';
import type {
  GetLandPropertyResponseType,
  GetBuildingPropertyResponseType,
  GetCondoPropertyResponseType,
  GetLandAndBuildingPropertyResponseType,
  GetSummaryDecisionResponseType,
} from '@shared/schemas/v1';
import type { CurrentAssignment } from '@features/appraisal/types/administration';
import { findAddressBySubDistrictCode } from '@/shared/data/thaiAddresses';

export const mapLandPropertyResponseToForm = (
  response: GetLandPropertyResponseType,
): createLandFormType => {
  const addressLookup = response.subDistrict
    ? findAddressBySubDistrictCode(response.subDistrict)
    : undefined;
  return {
    titles: (response as any).titles ?? [],
    propertyName: response.propertyName ?? '',
    latitude: response.latitude ?? 0,
    longitude: response.longitude ?? 0,
    subDistrict: response.subDistrict ?? '',
    subDistrictName: addressLookup?.subDistrictName ?? '',
    district: response.district ?? '',
    districtName: addressLookup?.districtName ?? '',
    province: response.province ?? '',
    provinceName: addressLookup?.provinceName ?? '',
    landOffice: response.landOffice ?? '',
    landDescription: response.landDescription ?? '',
    isOwnerVerified: response.isOwnerVerified ?? false,
    ownerName: response.ownerName ?? '',
    hasObligation: response.hasObligation ?? false,
    obligationDetails: response.obligationDetails ?? '',
    isLandLocationVerified: response.isLandLocationVerified ?? false,
    landCheckMethodType: response.landCheckMethodType ?? '',
    landCheckMethodTypeOther: response.landCheckMethodTypeOther ?? '',
    street: response.street ?? '',
    soi: response.soi ?? '',
    distanceFromMainRoad: response.distanceFromMainRoad ?? 0,
    village: response.village ?? '',
    addressLocation: response.addressLocation ?? '',
    landShapeType: response.landShapeType ?? '',
    urbanPlanningType: response.urbanPlanningType ?? '',
    landZoneType: response.landZoneType ?? [],
    plotLocationType: response.plotLocationType ?? [],
    plotLocationTypeOther: response.plotLocationTypeOther ?? '',
    landFillType: response.landFillType ?? '',
    landFillTypeOther: response.landFillTypeOther ?? '',
    landFillPercent: response.landFillPercent ?? 0,
    soilLevel: response.soilLevel ?? 0,
    accessRoadWidth: response.accessRoadWidth ?? 0,
    rightOfWay: response.rightOfWay ?? 0,
    roadFrontage: response.roadFrontage ?? 0,
    numberOfSidesFacingRoad: response.numberOfSidesFacingRoad ?? 0,
    roadPassInFrontOfLand: response.roadPassInFrontOfLand ?? '',
    landAccessibilityType: response.landAccessibilityType ?? '',
    landAccessibilityRemark: response.landAccessibilityRemark ?? '',
    roadSurfaceType: response.roadSurfaceType ?? '',
    roadSurfaceTypeOther: response.roadSurfaceTypeOther ?? '',
    publicUtilityType: response.publicUtilityType ?? [],
    publicUtilityTypeOther: response.publicUtilityTypeOther ?? '',
    landUseType: response.landUseType ?? [],
    landUseTypeOther: response.landUseTypeOther ?? '',
    landEntranceExitType: response.landEntranceExitType ?? [],
    landEntranceExitTypeOther: response.landEntranceExitTypeOther ?? '',
    transportationAccessType: response.transportationAccessType ?? [],
    transportationAccessTypeOther: response.transportationAccessTypeOther ?? '',
    propertyAnticipationType: response.propertyAnticipationType ?? '',
    isExpropriated: response.isExpropriated ?? false,
    expropriationRemark: response.expropriationRemark ?? '',
    isInExpropriationLine: response.isInExpropriationLine ?? false,
    expropriationLineRemark: response.expropriationLineRemark ?? '',
    royalDecree: response.royalDecree ?? '',
    isEncroached: response.isEncroached ?? false,
    encroachmentRemark: response.encroachmentRemark ?? '',
    encroachmentArea: response.encroachmentArea ?? 0,
    hasElectricity: response.hasElectricity ?? false,
    electricityDistance: response.electricityDistance ?? 0,
    isLandlocked: response.isLandlocked ?? false,
    landlockedRemark: response.landlockedRemark ?? '',
    isForestBoundary: response.isForestBoundary ?? false,
    forestBoundaryRemark: response.forestBoundaryRemark ?? '',
    otherLegalLimitations: response.otherLegalLimitations ?? '',
    evictionType: response.evictionType ?? [],
    evictionTypeOther: response.evictionTypeOther ?? '',
    allocationType: response.allocationType ?? '',
    northAdjacentArea: response.northAdjacentArea ?? '',
    northBoundaryLength: response.northBoundaryLength ?? 0,
    southAdjacentArea: response.southAdjacentArea ?? '',
    southBoundaryLength: response.southBoundaryLength ?? 0,
    eastAdjacentArea: response.eastAdjacentArea ?? '',
    eastBoundaryLength: response.eastBoundaryLength ?? 0,
    westAdjacentArea: response.westAdjacentArea ?? '',
    westBoundaryLength: response.westBoundaryLength ?? 0,
    pondArea: response.pondArea ?? 0,
    pondDepth: response.pondDepth ?? 0,
    hasBuilding: response.hasBuilding ?? false,
    hasBuildingOther: response.hasBuildingOther ?? '',
    remark: response.remark ?? '',
  };
};

export const mapBuildingPropertyResponseToForm = (
  response: GetBuildingPropertyResponseType,
): createBuildingFormType => {
  return {
    ownerName: response.ownerName ?? '',
    propertyName: response.propertyName ?? '',
    buildingNumber: response.buildingNumber ?? '',
    modelName: response.modelName ?? '',
    builtOnTitleNumber: response.builtOnTitleNumber ?? '',
    isOwnerVerified: response.isOwnerVerified ?? false,
    houseNumber: response.houseNumber ?? '',
    buildingConditionType: response.buildingConditionType ?? '',
    isUnderConstruction: response.isUnderConstruction ?? false,
    constructionCompletionPercent: response.constructionCompletionPercent ?? 100,
    constructionLicenseExpirationDate: response.constructionLicenseExpirationDate ?? '',
    isAppraisable: response.isAppraisable ?? false,
    hasObligation: response.hasObligation ?? false,
    obligationDetails: response.obligationDetails ?? '',
    buildingType: response.buildingType ?? '',
    buildingTypeOther: response.buildingTypeOther ?? '',
    numberOfFloors: response.numberOfFloors ?? 0,
    decorationType: response.decorationType ?? '',
    decorationTypeOther: response.decorationTypeOther ?? '',
    isEncroachingOthers: response.isEncroachingOthers ?? false,
    encroachingOthersRemark: response.encroachingOthersRemark ?? '',
    encroachingOthersArea: response.encroachingOthersArea ?? 0,
    buildingMaterialType: response.buildingMaterialType ?? '',
    buildingStyleType: response.buildingStyleType ?? '',
    isResidential: response.isResidential ?? false,
    buildingAge: response.buildingAge ?? 0,
    residentialRemark: response.residentialRemark ?? '',
    constructionStyleRemark: response.constructionStyleRemark ?? '',
    constructionStyleType: response.constructionStyleType ?? '',
    structureType: response.structureType ?? [],
    structureTypeOther: response.structureTypeOther ?? '',
    roofFrameType: response.roofFrameType ?? [],
    roofFrameTypeOther: response.roofFrameTypeOther ?? '',
    roofType: response.roofType ?? [],
    roofTypeOther: response.roofTypeOther ?? '',
    ceilingType: response.ceilingType ?? [],
    ceilingTypeOther: response.ceilingTypeOther ?? '',
    interiorWallType: response.interiorWallType ?? [],
    interiorWallTypeOther: response.interiorWallTypeOther ?? '',
    exteriorWallType: response.exteriorWallType ?? [],
    exteriorWallTypeOther: response.exteriorWallTypeOther ?? '',
    fenceType: response.fenceType ?? [],
    fenceTypeOther: response.fenceTypeOther ?? '',
    constructionType: response.constructionType ?? '',
    constructionTypeOther: response.constructionTypeOther ?? '',
    utilizationType: response.utilizationType ?? '',
    utilizationTypeOther: response.utilizationTypeOther ?? '',
    totalBuildingArea: response.totalBuildingArea ?? 0,
    buildingInsurancePrice: response.buildingInsurancePrice ?? 0,
    sellingPrice: response.sellingPrice ?? 0,
    forcedSalePrice: response.forcedSalePrice ?? 0,
    remark: response.remark ?? '',
  };
};

export const mapCondoPropertyResponseToForm = (
  response: GetCondoPropertyResponseType,
): createCondoFormType => {
  return {
    ownerName: response.ownerName ?? '',

    propertyName: response.propertyName ?? '',
    condoName: response.condoName ?? '',
    buildingNumber: response.buildingNumber ?? '',
    modelName: response.modelName ?? '',
    builtOnTitleNumber: response.builtOnTitleNumber ?? '',
    condoRegistrationNumber: response.condoRegistrationNumber ?? '',
    roomNumber: response.roomNumber ?? '',
    floorNumber: response.floorNumber ?? 0,
    usableArea: response.usableArea ?? 0,

    latitude: response.latitude ?? 0,
    longitude: response.longitude ?? 0,

    subDistrict: response.subDistrict ?? '',
    district: response.district ?? '',
    province: response.province ?? '',
    landOffice: response.landOffice ?? '',

    isOwnerVerified: response.isOwnerVerified ?? false,
    buildingConditionType: response.buildingConditionType ?? '',
    hasObligation: response.hasObligation ?? false,
    obligationDetails: response.obligationDetails ?? '',
    isDocumentValidated: response.isDocumentValidated ?? true,

    locationType: response.locationType ?? '',
    street: response.street ?? '',
    soi: response.soi ?? '',
    distanceFromMainRoad: response.distanceFromMainRoad ?? 0,
    accessRoadWidth: response.accessRoadWidth ?? 0,
    rightOfWay: response.rightOfWay ?? 0,
    roadSurfaceType: response.roadSurfaceType ?? '',
    publicUtilityType: response.publicUtilityType ?? [],
    publicUtilityTypeOther: response.publicUtilityTypeOther ?? '',

    decorationType: response.decorationType ?? '',
    decorationTypeOther: response.decorationTypeOther ?? '',
    buildingAge: response.buildingAge ?? 0,
    numberOfFloors: response.numberOfFloors ?? 0,
    buildingFormType: response.buildingFormType ?? '',
    constructionMaterialType: response.constructionMaterialType ?? '',

    roomLayoutType: response.roomLayoutType ?? '',
    roomLayoutTypeOther: response.roomLayoutTypeOther ?? '',
    locationViewType: response.locationViewType ?? [],
    groundFloorMaterialType: response.groundFloorMaterialType ?? '',
    groundFloorMaterialTypeOther: response.groundFloorMaterialTypeOther ?? '',
    upperFloorMaterialType: response.upperFloorMaterialType ?? '',
    upperFloorMaterialTypeOther: response.upperFloorMaterialTypeOther ?? '',
    bathroomFloorMaterialType: response.bathroomFloorMaterialType ?? '',
    bathroomFloorMaterialTypeOther: response.bathroomFloorMaterialTypeOther ?? '',
    roofType: response.roofType ?? '',
    roofTypeOther: response.roofTypeOther ?? '',

    areaDetails: response.areaDetails ?? [],
    totalBuildingArea: response.totalBuildingArea ?? 0,

    isExpropriated: response.isExpropriated ?? false,
    expropriationRemark: response.expropriationRemark ?? '',
    isInExpropriationLine: response.isInExpropriationLine ?? false,
    expropriationLineRemark: response.expropriationLineRemark ?? '',
    royalDecree: response.royalDecree ?? '',
    isForestBoundary: response.isForestBoundary ?? false,
    forestBoundaryRemark: response.forestBoundaryRemark ?? '',

    facilityType: response.facilityType ?? [],
    facilityTypeOther: response.facilityTypeOther ?? '',
    environmentType: response.environmentType ?? [],

    buildingInsurancePrice: response.buildingInsurancePrice ?? 0,
    sellingPrice: response.sellingPrice ?? 0,
    forcedSalePrice: response.forceSellingPrice ?? 0,

    remark: response.remark ?? '',
  };
};

export const mapLandAndBuildingPropertyResponseToForm = (
  response: GetLandAndBuildingPropertyResponseType,
): createLandAndBuildingFormType => {
  const addressLookup = response.subDistrict
    ? findAddressBySubDistrictCode(response.subDistrict)
    : undefined;
  return {
    titles: (response as any).titles ?? [],
    propertyName: response.propertyName ?? '',
    latitude: response.latitude ?? 0,
    longitude: response.longitude ?? 0,
    subDistrict: response.subDistrict ?? '',
    subDistrictName: addressLookup?.subDistrictName ?? '',
    district: response.district ?? '',
    districtName: addressLookup?.districtName ?? '',
    province: response.province ?? '',
    provinceName: addressLookup?.provinceName ?? '',
    landOffice: response.landOffice ?? '',
    landDescription: response.landDescription ?? '',
    isOwnerVerified: response.isOwnerVerified ?? false,
    ownerName: response.ownerName ?? '',
    hasObligation: response.hasObligation ?? false,
    obligationDetails: response.obligationDetails ?? '',
    isLandLocationVerified: response.isLandLocationVerified ?? false,
    landCheckMethodType: response.landCheckMethodType ?? '',
    landCheckMethodTypeOther: response.landCheckMethodTypeOther ?? '',
    street: response.street ?? '',
    soi: response.soi ?? '',
    distanceFromMainRoad: response.distanceFromMainRoad ?? 0,
    village: response.village ?? '',
    addressLocation: response.addressLocation ?? '',
    landShapeType: response.landShapeType ?? '',
    urbanPlanningType: response.urbanPlanningType ?? '',
    landZoneType: response.landZoneType ?? [],
    plotLocationType: response.plotLocationType ?? [],
    plotLocationTypeOther: response.plotLocationOther ?? '',
    landFillType: response.landFillType ?? '',
    landFillTypeOther: response.landFillTypeOther ?? '',
    landFillPercent: response.landFillPercent ?? 0,
    soilLevel: response.soilLevel ?? 0,
    accessRoadWidth: response.accessRoadWidth ?? 0,
    rightOfWay: response.rightOfWay ?? 0,
    roadFrontage: response.roadFrontage ?? 0,
    numberOfSidesFacingRoad: response.numberOfSidesFacingRoad ?? 0,
    roadPassInFrontOfLand: response.roadPassInFrontOfLand ?? '',
    landAccessibilityType: response.landAccessibilityType ?? '',
    landAccessibilityRemark: response.landAccessibilityRemark ?? '',
    roadSurfaceType: response.roadSurfaceType ?? '',
    roadSurfaceTypeOther: response.roadSurfaceTypeOther ?? '',
    publicUtilityType: response.publicUtilityType ?? [],
    publicUtilityTypeOther: response.publicUtilityTypeOther ?? '',
    landUseType: response.landUseType ?? [],
    landUseTypeOther: response.landUseTypeOther ?? '',
    landEntranceExitType: response.landEntranceExitType ?? [],
    landEntranceExitTypeOther: response.landEntranceExitTypeOther ?? '',
    transportationAccessType: response.transportationAccessType ?? [],
    transportationAccessTypeOther: response.transportationAccessTypeOther ?? '',
    propertyAnticipationType: response.propertyAnticipationType ?? '',
    isExpropriated: response.isExpropriated ?? false,
    expropriationRemark: response.expropriationRemark ?? '',
    isInExpropriationLine: response.isInExpropriationLine ?? false,
    expropriationLineRemark: response.expropriationLineRemark ?? '',
    royalDecree: response.royalDecree ?? '',
    isEncroached: response.isEncroached ?? false,
    encroachmentRemark: response.encroachmentRemark ?? '',
    encroachmentArea: response.encroachmentArea ?? 0,
    hasElectricity: response.hasElectricity ?? false,
    electricityDistance: response.electricityDistance ?? 0,
    isLandlocked: response.isLandlocked ?? false,
    landlockedRemark: response.landlockedRemark ?? '',
    isForestBoundary: response.isForestBoundary ?? false,
    forestBoundaryRemark: response.forestBoundaryRemark ?? '',
    otherLegalLimitations: response.otherLegalLimitations ?? '',
    evictionType: response.evictionType ?? [],
    evictionTypeOther: response.evictionTypeOther ?? '',
    allocationType: response.allocationType ?? '',
    northAdjacentArea: response.northAdjacentArea ?? '',
    northBoundaryLength: response.northBoundaryLength ?? 0,
    southAdjacentArea: response.southAdjacentArea ?? '',
    southBoundaryLength: response.southBoundaryLength ?? 0,
    eastAdjacentArea: response.eastAdjacentArea ?? '',
    eastBoundaryLength: response.eastBoundaryLength ?? 0,
    westAdjacentArea: response.westAdjacentArea ?? '',
    westBoundaryLength: response.westBoundaryLength ?? 0,
    pondArea: response.pondArea ?? 0,
    pondDepth: response.pondDepth ?? 0,

    buildingNumber: response.buildingNumber ?? '',
    modelName: response.modelName ?? '',
    builtOnTitleNumber: response.builtOnTitleNumber ?? '',
    houseNumber: response.houseNumber ?? '',
    buildingConditionType: response.buildingConditionType ?? '',
    isUnderConstruction: response.isUnderConstruction ?? false,
    constructionCompletionPercent: response.constructionCompletionPercent ?? 100,
    constructionLicenseExpirationDate: response.constructionLicenseExpirationDate ?? '',
    isAppraisable: response.isAppraisable ?? false,
    buildingType: response.buildingType ?? '',
    buildingTypeOther: response.buildingTypeOther ?? '',
    numberOfFloors: response.numberOfFloors ?? 0,
    decorationType: response.decorationType ?? '',
    decorationTypeOther: response.decorationTypeOther ?? '',
    isEncroachingOthers: response.isEncroachingOthers ?? false,
    encroachingOthersRemark: response.encroachingOthersRemark ?? '',
    encroachingOthersArea: response.encroachingOthersArea ?? 0,
    buildingMaterialType: response.buildingMaterialType ?? '',
    buildingStyleType: response.buildingStyleType ?? '',
    isResidential: response.isResidential ?? false,
    buildingAge: response.buildingAge ?? 0,
    residentialRemark: response.residentialRemark ?? '',
    constructionStyleRemark: response.constructionStyleRemark ?? '',
    constructionStyleType: response.constructionStyleType ?? '',
    structureType: response.structureType ?? [],
    structureTypeOther: response.structureTypeOther ?? '',
    roofFrameType: response.roofFrameType ?? [],
    roofFrameTypeOther: response.roofFrameTypeOther ?? '',
    roofType: response.roofType ?? [],
    roofTypeOther: response.roofTypeOther ?? '',
    ceilingType: response.ceilingType ?? [],
    ceilingTypeOther: response.ceilingTypeOther ?? '',
    interiorWallType: response.interiorWallType ?? [],
    interiorWallTypeOther: response.interiorWallTypeOther ?? '',
    exteriorWallType: response.exteriorWallType ?? [],
    exteriorWallTypeOther: response.exteriorWallTypeOther ?? '',
    fenceType: response.fenceType ?? [],
    fenceTypeOther: response.fenceTypeOther ?? '',
    constructionType: response.constructionType ?? '',
    constructionTypeOther: response.constructionTypeOther ?? '',
    utilizationType: response.utilizationType ?? '',
    utilizationTypeOther: response.utilizationTypeOther ?? '',
    totalBuildingArea: response.totalBuildingArea ?? 0,
    buildingInsurancePrice: response.buildingInsurancePrice ?? 0,
    sellingPrice: response.sellingPrice ?? 0,
    forcedSalePrice: response.forcedSalePrice ?? 0,
    remark: response.buildingRemark ?? '',
  };
};

export const mapLandAndBuildingPMAPropertyResponseToForm = (
  response: GetLandAndBuildingPMAPropertyByIdResultType,
): landAndBuildingPMAFormType => {
  const addressLookup = response.subDistrict
    ? findAddressBySubDistrictCode(response.subDistrict)
    : undefined;
  return {
    buildingInsurancePrice: response.buildingInsurancePrice ?? 0,
    sellingPrice: response.sellingPrice ?? 0,
    forcedSalePrice: response.forcedSalePrice ?? 0,
    titleNo: response.titleNo ?? '',
    rawang: response.rawang ?? '',
    landNo: response.landNo ?? '',
    surveyNo: response.surveyNo ?? '',
    bookNumber: response.bookNumber ?? '',
    pageNumber: response.pageNumber ?? '',
    areaRai: response.areaRai ?? 0,
    areaNgan: response.areaNgan ?? 0,
    areaSquareWa: response.areaSquareWa ?? 0,
    subDistrict: response.subDistrict ?? '',
    subDistrictName: addressLookup?.subDistrictName ?? '',
    district: response.district ?? '',
    districtName: addressLookup?.districtName ?? '',
    province: response.province ?? '',
    provinceName: addressLookup?.provinceName ?? '',
  };
};

export const mapCondoPMAPropertyResponseToForm = (
  response: GetCondoPMAPropertyByIdResultType,
): condoPMAFormType => {
  const addressLookup = response.subDistrict
    ? findAddressBySubDistrictCode(response.subDistrict)
    : undefined;
  return {
    buildingInsurancePrice: response.buildingInsurancePrice ?? 0,
    sellingPrice: response.sellingPrice ?? 0,
    forcedSalePrice: response.forcedSalePrice ?? 0,
    builtOnTitleNumber: response.builtOnTitleNumber ?? '',
    condoRegistrationNumber: response.condoRegistrationNumber ?? '',
    roomNumber: response.roomNumber ?? '',
    floorNumber: response.floorNumber ?? 0,
    buildingNumber: response.buildingNumber ?? '',
    condoName: response.condoName ?? '',
    subDistrict: response.subDistrict ?? '',
    subDistrictName: addressLookup?.subDistrictName ?? '',
    district: response.district ?? '',
    districtName: addressLookup?.districtName ?? '',
    province: response.province ?? '',
    provinceName: addressLookup?.provinceName ?? '',
  };
};

export const mapAssignmentResponseToForm = (response: CurrentAssignment) => {
  return {
    assignmentType: response.assignmentType.toLowerCase() as 'internal' | 'external',
    assignmentMethod: response.assignmentMethod.toLowerCase() as
      | 'manual'
      | 'roundrobin'
      | 'quotation',
    staffId: response.assigneeUserId ?? null,
    companyId: response.assigneeCompanyId ?? null,
    followupStaffId: response.internalAppraiserId ?? null,
    selectedStaff: null as null,
    selectedCompany: null as null,
    selectedFollowupStaff: null as null,
    remarks: '',
  };
};

export const mapSummaryDecisionResponseToForm = (
  response: GetSummaryDecisionResponseType,
): summaryDecisionFormType => {
  return {
    dateTime: response.dateTime ?? '',
    appraisalPrice: response.appraisalPrice ?? 0,
    buildingInsurancePrice: response.buildingInsurancePrice ?? 0,
    decision: '',
    forcedSalePrice: response.forcedSalePrice ?? 0,
    priceVerification: response.priceVerification ?? true,
    groupValuations: response.groupValuations ?? [],
    landTitle: response.landTitle ?? [],
    condition: response.condition ?? '',
    remark: response.remark ?? '',
    remarkDecision: '',
    opinionAppraiser: response.opinionAppraiser ?? '',
    opinionCommittee: response.opinionCommittee ?? '',
    specialAssumption: response.specialAssumption ?? '',
  };
};
